// tailwinduikit/reels/angular/src/app/pages/gallery-category/gallery-category.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-gallery-category',
  templateUrl: './gallery-category.component.html',
  styleUrls: ['./gallery-category.component.css'],
})
export class GalleryCategoryComponent {
  myFlag = true;
  public MenuHandler3 = () => {
    if (this.myFlag) {
      document.getElementById('list2').classList.remove('hidden');
      document.getElementById('close2').classList.remove('hidden');
      document.getElementById('open2').classList.add('hidden');
      this.myFlag = false;
    } else {
      document.getElementById('list2').classList.add('hidden');
      document.getElementById('close2').classList.add('hidden');
      document.getElementById('open2').classList.remove('hidden');
      this.myFlag = true;
    }
  };
}

<app-header></app-header>
<div class="xl:mx-auto xl:container">
    <h1 class="text-4xl font-bold text-color-black xl:px-0 px-4">Gallery</h1>
    <!-- categories -->
    <div class="lg:flex items-center mt-16 hidden">
        <a href="/gallery" class="cursor-pointer"> <div class="text-base relative font-light text-color-black border-r border-color-gray leading-4 border-r pl-5 pr-11">All</div></a>
        <a href="/gallery" class="cursor-pointer">
            <div class="text-hr px-11 text-base relative font-light text-color-black leading-4 border-r border-color-gray">Nature</div>
        </a>
        <a href="/gallery" class="cursor-pointer">
            <div class="px-11 text-hr text-base relative font-light text-color-black leading-4 border-r border-color-gray">Wedding</div>
        </a>
        <a href="/gallery" class="cursor-pointer">
            <div class="px-11 text-hr text-base relative font-light text-color-black leading-4 border-r border-color-gray">Street</div>
        </a>
        <a href="/gallery" class="cursor-pointer">
            <div class="px-11 text-hr text-base relative font-light text-color-black leading-4 border-r border-color-gray">People</div>
        </a>
        <a href="javascript:void(0)" class="cursor-pointer">
            <div class="px-11 text-hr text-base relative font-light text-color-black leading-4">
                Architecture
                <hr class="border-2 border-gold-color bg-gold-color w-14 right-0 mr-14 mt-1 rounded-full absolute" />
            </div>
        </a>
    </div>
    <!-- mobile -->
    <div class="lg:hidden block xl:px-0 px-4">
        <div class="relative">
            <div class="bg-gold-color flex items-center justify-between rounded w-full border border-gold-color cursor-pointer mt-8" (click)="MenuHandler3()">
                <p class="pl-3 py-3 text-white text-sm leading-3 tracking-normal font-normal">categories</p>
                <div class="cursor-pointer text-white mr-3">
                    <svg xmlns="http://www.w3.org/2000/svg" id="close2" class="icon icon-tabler hidden icon-tabler-chevron-up" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" />
                        <polyline points="6 15 12 9 18 15" />
                    </svg>
                    <svg xmlns="http://www.w3.org/2000/svg" id="open2" class="icon icon-tabler icon-tabler-chevron-up" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" />
                        <polyline points="6 9 12 15 18 9" />
                    </svg>
                </div>
            </div>
            <ul class="transition duration-300 opacity-100 hidden ease-out bg-color-black shadow rounded mt-2 py-1 w-full absolute z-40" id="list2">
                <a href="/gallery"> <li class="cursor-pointer text-white text-sm leading-3 tracking-normal py-3 hover-gold px-3 font-bold">All</li> </a>
                <a href="/gallery"> <li class="cursor-pointer text-white font-bold text-sm leading-3 tracking-normal py-3 hover-gold px-3">Nature</li> </a>
                <a href="/gallery"> <li class="cursor-pointer text-white font-bold text-sm leading-3 tracking-normal py-3 hover-gold px-3">Wedding</li> </a>
                <a href="/gallery"> <li class="cursor-pointer text-white font-bold text-sm leading-3 tracking-normal py-3 hover-gold px-3">Street</li> </a>
                <a href="/gallery"> <li class="cursor-pointer text-white font-bold text-sm leading-3 tracking-normal py-3 hover-gold px-3">People</li> </a>
                <a href="javascript:void(0)"> <li class="cursor-pointer text-white font-bold text-sm leading-3 tracking-normal py-3 hover-gold px-3">Architecture</li> </a>
            </ul>
        </div>
    </div>
    <!-- hero -->
    <div class="flex items-center justify-center relative mt-36 2xl:block hidden">
        <div class="flex items-center justify-center">
            <img src="https://cdn.tuk.dev/assets/templates/reels/archi1.png" class="absolute left-0 z-0" />
            <img src="https://cdn.tuk.dev/assets/templates/reels/archi2.png" class="relative z-10" />
            <img src="https://cdn.tuk.dev/assets/templates/reels/archi3.png" class="absolute right-0 z-0" />
        </div>
    </div>
    <div class="flex relative lg:mt-36 mt-16 2xl:hidden block">
        <div class="relative h-full flex items-center justify-center w-full">
            <div class="flex items-center justify-center relative">
                <img src="https://cdn.tuk.dev/assets/templates/reels/archi1.png" class="absolute xl:w-1/4 w-1/6 left-0 xl:-ml-36 xl:ml-0 lg:ml-12 md:ml-10 sm:ml-8 ml-7" />
                <img src="https://cdn.tuk.dev/assets/templates/reels/archi2.png" class="xl:w-10/12 w-7/12 z-20" />
                <img src="https://cdn.tuk.dev/assets/templates/reels/archi3.png" class="absolute right-0 xl:w-1/4 w-1/6 z-0 xl:-mr-36 xl:mr-0 lg:mr-12 md:mr-10 sm:mr-8 mr-7" />
            </div>
        </div>
    </div>
</div>
<div class="w-full bg-peach 2xl:-mt-96 xl:-mt-80 lg:-mt-56 sm:-mt-32 -mt-16 xl:px-0 px-4">
    <div class="2xl:pt-96 xl:pt-72 lg:pt-32 pt-4 mx-auto container">
        <div class="sm:flex items-center justify-between 2xl:pt-32 lg:pt-40 2xl:pb-24 sm:pt-32 pt-16 lg:pb-16 sm:pb-8 pb-2">
            <h1 class="xl:text-8xl text-4xl font-bold text-off-white">ARCHITECTURE</h1>
        </div>
    </div>
</div>

<!-- hero -->
<!-- body -->
<!-- Featured Work -->
<div class="my-16 w-full mx-auto container xl:px-0 px-8">
    <div class="lg:flex items-center justify-between">
        <div class="w-2/5 lg:block hidden">
            <hr class="" />
        </div>
        <div class="text-center">
            <p class="text-color-black text-center text-base font-light">Featured Work</p>
        </div>
        <div class="w-2/5 lg:block hidden">
            <hr />
        </div>
    </div>
    <div class="md:mt-48 mt-40">
        <div class="flex xl:flex-row flex-col items-center md:justify-between justify-center">
            <div class="xl:mr-7 sm:flex sm:items-center sm:justify-center xl:mt-0 mt-16 xl:w-1/3 w-full">
                <div class="bg-peach flex px-5 items-center justify-center relative xl:w-full sm:w-1/2 h-full pb-32">
                    <img class="xl:w-full -mt-32" src="https://cdn.tuk.dev/assets/templates/reels/cat1.png" />
                    <div class="absolute bottom-0 left-0 mb-12 ml-7 flex items-center">
                        <hr class="w-16 border-2 bg-black border-black" />
                        <p class="text-2xl font-light leading-normal ml-2 text-color-black">New Building</p>
                    </div>
                </div>
            </div>
            <div class="xl:mr-7 sm:flex sm:items-center sm:justify-center xl:mt-0 mt-48 xl:w-1/3 w-full lg:-mb-48">
                <div class="bg-peach flex px-5 items-center justify-center relative xl:w-full sm:w-1/2 h-full pb-32">
                    <img class="xl:w-full -mt-32" src="https://cdn.tuk.dev/assets/templates/reels/cat1.png" />
                    <div class="absolute bottom-0 left-0 mb-12 ml-7 flex items-center">
                        <hr class="w-16 border-2 bg-black border-black" />
                        <p class="text-2xl font-light leading-normal ml-2 text-color-black">New Building</p>
                    </div>
                </div>
            </div>
            <div class="sm:flex sm:items-center sm:justify-center xl:mt-0 lg:mt-96 mt-48 xl:w-1/3 w-full">
                <div class="bg-peach flex px-5 items-center justify-center relative xl:w-full sm:w-1/2 h-full pb-32">
                    <img class="xl:w-full -mt-32" src="https://cdn.tuk.dev/assets/templates/reels/cat1.png" />
                    <div class="absolute bottom-0 left-0 mb-12 ml-7 flex items-center">
                        <hr class="w-16 border-2 bg-black border-black" />
                        <p class="text-2xl font-light leading-normal ml-2 text-color-black">New Building</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="flex xl:flex-row flex-col items-center xl:justify-between justify-center xl:mt-48">
            <div class="xl:mr-7 sm:flex sm:items-center sm:justify-center xl:mt-0 mt-48 xl:w-1/3 w-full">
                <div class="bg-peach flex px-5 items-center justify-center relative xl:w-full sm:w-1/2 h-full pb-32">
                    <img class="xl:w-full -mt-32" src="https://cdn.tuk.dev/assets/templates/reels/cat1.png" />
                    <div class="absolute bottom-0 left-0 mb-12 ml-7 flex items-center">
                        <hr class="w-16 border-2 bg-black border-black" />
                        <p class="text-2xl font-light leading-normal ml-2 text-color-black">New Building</p>
                    </div>
                </div>
            </div>
            <div class="xl:mr-7 sm:flex sm:items-center sm:justify-center xl:mt-0 mt-48 xl:w-1/3 w-full lg:-mb-48">
                <div class="bg-peach flex px-5 items-center justify-center relative xl:w-full sm:w-1/2 h-full pb-32">
                    <img class="xl:w-full -mt-32" src="https://cdn.tuk.dev/assets/templates/reels/cat1.png" />
                    <div class="absolute bottom-0 left-0 mb-12 ml-7 flex items-center">
                        <hr class="w-16 border-2 bg-black border-black" />
                        <p class="text-2xl font-light leading-normal ml-2 text-color-black">New Building</p>
                    </div>
                </div>
            </div>
            <div class="sm:flex sm:items-center sm:justify-center xl:mt-0 lg:mt-96 mt-48 xl:w-1/3 w-full">
                <div class="bg-peach flex px-5 items-center justify-center relative xl:w-full sm:w-1/2 h-full pb-32">
                    <img class="xl:w-full -mt-32" src="https://cdn.tuk.dev/assets/templates/reels/cat1.png" />
                    <div class="absolute bottom-0 left-0 mb-12 ml-7 flex items-center">
                        <hr class="w-16 border-2 bg-black border-black" />
                        <p class="text-2xl font-light leading-normal ml-2 text-color-black">New Building</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Featured Work -->
<app-footer></app-footer>

// tailwinduikit/reels/vue/src/components/gallery_category/index.vue
<template>
    <h1 class="text-4xl font-bold text-color-black xl:px-0 px-4">Gallery</h1>
    <!-- categories -->
    <div class="lg:flex items-center mt-16 hidden">
        <router-link to="/ReelsGallery" class="cursor-pointer">
            <div class="text-base relative font-light text-color-black border-color-gray leading-4 border-r pl-5 pr-11">
                All
                <hr v-if="$route.path === '/ReelsGallery'"
                    class="border-2 border-gold-color bg-gold-color w-14 right-0 mr-5 mt-1 rounded-full absolute" />
            </div>
        </router-link>
        <a href="#" class="cursor-pointer">
            <div class="text-hr px-11 text-base relative font-light text-color-black leading-4 border-r border-color-gray">Nature</div>
        </a>
        <a href="#" class="cursor-pointer">
            <div class="px-11 text-hr text-base relative font-light text-color-black leading-4 border-r border-color-gray">Wedding</div>
        </a>
        <a href="#" class="cursor-pointer">
            <div class="px-11 text-hr text-base relative font-light text-color-black leading-4 border-r border-color-gray">Street</div>
        </a>
        <a href="#" class="cursor-pointer">
            <div class="px-11 text-hr text-base relative font-light text-color-black leading-4 border-r border-color-gray">People</div>
        </a>
        <router-link to="/GalleryCategory" class="cursor-pointer">
            <div class="px-11 text-hr text-base relative font-light text-color-black leading-4">
                Architecture
                <hr 
                    v-if="$route.path === '/GalleryCategory'"
                    class="border-2 border-gold-color bg-gold-color w-14 right-0 mr-14 mt-1 rounded-full absolute" />
            </div>
        </router-link>
    </div>
    <!-- mobile -->
    <div class="lg:hidden block xl:px-0 px-4">
        <div class="relative">
            <div class="bg-gold-color flex items-center justify-between rounded w-full border border-gold-color cursor-pointer mt-8" @click="MenuHandler3()">
                <p class="pl-3 py-3 text-white text-sm leading-3 tracking-normal font-normal">categories</p>
                <div class="cursor-pointer text-white mr-3">
                    <svg xmlns="http://www.w3.org/2000/svg" id="close2" class="icon icon-tabler hidden icon-tabler-chevron-up" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" />
                        <polyline points="6 15 12 9 18 15" />
                    </svg>
                    <svg xmlns="http://www.w3.org/2000/svg" id="open2" class="icon icon-tabler icon-tabler-chevron-up" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" />
                        <polyline points="6 9 12 15 18 9" />
                    </svg>
                </div>
            </div>
            <ul class="transition duration-300 opacity-100 hidden ease-out bg-color-black shadow rounded mt-2 py-1 w-full absolute z-40" id="list2">
                <router-link to="/ReelsGallery"> <li class="cursor-pointer text-white text-sm leading-3 tracking-normal py-3 hover-gold px-3 font-bold">All</li> </router-link>
                <a href="#"> <li class="cursor-pointer text-white font-bold text-sm leading-3 tracking-normal py-3 hover-gold px-3">Nature</li> </a>
                <a href="#"> <li class="cursor-pointer text-white font-bold text-sm leading-3 tracking-normal py-3 hover-gold px-3">Wedding</li> </a>
                <a href="#"> <li class="cursor-pointer text-white font-bold text-sm leading-3 tracking-normal py-3 hover-gold px-3">Street</li> </a>
                <a href="#"> <li class="cursor-pointer text-white font-bold text-sm leading-3 tracking-normal py-3 hover-gold px-3">People</li> </a>
                <router-link to="/GalleryCategory"> <li class="cursor-pointer text-white font-bold text-sm leading-3 tracking-normal py-3 hover-gold px-3">Architecture</li> </router-link>
            </ul>
        </div>
    </div>
</template>

<script>
import MenuHandler3 from '@/mixins'
export default {
    mixins: [MenuHandler3]
}
</script>
