// tailwinduikit/prodify/vue/src/components/4_by_4_grid_with_gradient_backgro/index.vue
<template>
    <!-- <div class="my-14"> -->
    <div class="mx-auto container py-10 lg:pt-52 lg:pb-20">
        <h1 class="text-color font-black f-f-l text-center text-3xl lg:text-7xl">2000+ products built</h1>
    </div>
    <div class="bg-linear-about-us py-16">
        <div class="mx-auto container px-4 xl:px-0">
            <div class="grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
                <div v-for="index in 16" :key="index">
                    <div class="w-full h-full">
                        <img class="w-full h-full shadow-xl rounded-xl" src="https://cdn.tuk.dev/assets/templates/prodify/About-us_card.png" alt="" />
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- </div> -->
</template>

// tailwinduikit/prodify/react/components/4_by_4_grid_with_gradient_backgro/index.js
import React from "react";
function IndexPage() {
    return (
        <>
            <div className="mx-auto container py-10  lg:pt-52 lg:pb-20">
                <h1 className="text-color font-black f-f-l text-center text-3xl lg:text-7xl">2000+ products built</h1>
            </div>
            <div className="bg-linear-about-us py-16">
                <div className="mx-auto container px-4 xl:px-0">
                    <div className="grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4  gap-8">
                        <div className="w-full h-full ">
                            <img className="w-full h-full shadow-xl rounded-xl" src="https://cdn.tuk.dev/assets/templates/prodify/About-us_card.png" alt />
                        </div>
                        <div className="w-full h-full">
                            <img className="w-full h-full shadow-xl rounded-xl" src="https://cdn.tuk.dev/assets/templates/prodify/About-us_card.png" alt />
                        </div>
                        <div className="w-full h-full">
                            <img className="w-full h-full shadow-xl rounded-xl" src="https://cdn.tuk.dev/assets/templates/prodify/About-us_card.png" alt />
                        </div>
                        <div className="w-full h-full">
                            <img className="w-full h-full shadow-xl rounded-xl" src="https://cdn.tuk.dev/assets/templates/prodify/About-us_card.png" alt />
                        </div>
                        <div className="w-full h-full">
                            <img className="w-full h-full shadow-xl rounded-xl" src="https://cdn.tuk.dev/assets/templates/prodify/About-us_card.png" alt />
                        </div>
                        <div className="w-full h-full">
                            <img className="w-full h-full shadow-xl rounded-xl" src="https://cdn.tuk.dev/assets/templates/prodify/About-us_card.png" alt />
                        </div>
                        <div className="w-full h-full">
                            <img className="w-full h-full shadow-xl rounded-xl" src="https://cdn.tuk.dev/assets/templates/prodify/About-us_card.png" alt />
                        </div>
                        <div className="w-full h-full">
                            <img className="w-full h-full shadow-xl rounded-xl" src="https://cdn.tuk.dev/assets/templates/prodify/About-us_card.png" alt />
                        </div>
                        <div className="w-full h-full">
                            <img className="w-full h-full shadow-xl rounded-xl" src="https://cdn.tuk.dev/assets/templates/prodify/About-us_card.png" alt />
                        </div>
                        <div className="w-full h-full">
                            <img className="w-full h-full shadow-xl rounded-xl" src="https://cdn.tuk.dev/assets/templates/prodify/About-us_card.png" alt />
                        </div>
                        <div className="w-full h-full">
                            <img className="w-full h-full shadow-xl rounded-xl" src="https://cdn.tuk.dev/assets/templates/prodify/About-us_card.png" alt />
                        </div>
                        <div className="w-full h-full">
                            <img className="w-full h-full shadow-xl rounded-xl" src="https://cdn.tuk.dev/assets/templates/prodify/About-us_card.png" alt />
                        </div>
                        <div className="w-full h-full">
                            <img className="w-full h-full shadow-xl rounded-xl" src="https://cdn.tuk.dev/assets/templates/prodify/About-us_card.png" alt />
                        </div>
                        <div className="w-full h-full">
                            <img className="w-full h-full shadow-xl rounded-xl" src="https://cdn.tuk.dev/assets/templates/prodify/About-us_card.png" alt />
                        </div>
                        <div className="w-full h-full">
                            <img className="w-full h-full shadow-xl rounded-xl" src="https://cdn.tuk.dev/assets/templates/prodify/About-us_card.png" alt />
                        </div>
                        <div className="w-full h-full">
                            <img className="w-full h-full shadow-xl rounded-xl" src="https://cdn.tuk.dev/assets/templates/prodify/About-us_card.png" alt />
                        </div>
                    </div>
                </div>
            </div>
            <style>
                {`.bg-linear-about-us {
            background: linear-gradient(180deg, #FF8584 0%, #DEF2BC 100%);
        }

        .bg-button-color-about-us {
            background-color: #EDF2F7;
        }

        .bg-linear-button {
            background: rgba(255, 255, 255, 0.3);
            border-radius: 6px;
        }

        .top-100 {
            animation: slideDown .5s ease-in-out;
        }

        @keyframes slideDown {
            0% {
                top: -50%;
            }

            100% {
                top: 0;
            }
        }

        * {
            outline: none !important;
            -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
            -webkit-tap-highlight-color: transparent;
        }`}
            </style>
        </>
    );
}

export default IndexPage;
