// tailwinduikit/wecare/angular/src/app/components/blue-background-with-yellow-sphere/blue-background-with-yellow-sphere.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'app-blue-background-with-yellow-sphere',
    templateUrl: './blue-background-with-yellow-sphere.component.html',
    styleUrls: ['./blue-background-with-yellow-sphere.component.css'],
})
export class BlueBackgroundWithYellowSphereComponent implements OnInit {
    constructor() {}

    ngOnInit(): void {}
}

<footer>
    <div class="mt-12 relative pt-6">
        <img class="w-8 lg:w-auto absolute inset-0 m-auto mr-12 z-10 -mt-4 lg:-mt-8" src="https://cdn.tuk.dev/assets/templates/weCare/ball-large.png" />
        <img src="https://i.ibb.co/C9d3C0b/footer-bg.png" class="absolute inset-0 w-full h-full object-cover object-center" />
        <div class="container relative z-10 mx-auto lg:flex justify-between px-6 pt-8 lg:pt-32 pb-6 lg:pb-28">
            <div class="lg:w-1/4 pb-12 lg:pb-0">
                <img class="mb-8" src="https://cdn.tuk.dev/assets/templates/weCare/logo-white.png" alt="logo" />
                <p class="text-white text-xl">4140 Parker Rd. Allentown, New Mexico 31134</p>
            </div>
            <div class="lg:w-1/2 sm:flex justify-between lg:justify-end">
                <div class="lg:pr-24 pb-12 lg:pb-0">
                    <h3 class="mb-6 text-lg text-white font-bold">Links</h3>
                    <ul class="text-white">
                        <li class="mb-3"><a href="#">Products</a></li>
                        <li class="mb-3"><a href="#">Claims</a></li>
                        <li class="mb-3"><a href="#">Renewals</a></li>
                        <li><a href="#">Support</a></li>
                    </ul>
                </div>
                <div class="lg:pr-24 pb-12 lg:pb-0">
                    <h3 class="mb-6 text-lg text-white font-bold">Services</h3>
                    <ul class="text-white">
                        <li class="mb-3"><a href="#">Products</a></li>
                        <li class="mb-3"><a href="#">Claims</a></li>
                        <li class="mb-3"><a href="#">Renewals</a></li>
                        <li><a href="#">Support</a></li>
                    </ul>
                </div>
                <div>
                    <h3 class="mb-6 text-lg text-white font-bold">About</h3>
                    <ul class="text-white">
                        <li class="mb-3"><a href="#">Products</a></li>
                        <li class="mb-3"><a href="#">Claims</a></li>
                        <li class="mb-3"><a href="#">Renewals</a></li>
                        <li><a href="#">Support</a></li>
                    </ul>
                </div>
            </div>
            <div class="lg:w-1/4 flex lg:justify-end items-end mt-12 lg:mt-0">
                <div class="bg-white p-2 rounded-full mr-2.5">
                    <img src="https://cdn.tuk.dev/assets/templates/weCare/fb.png" />
                </div>
                <div class="bg-white p-2 rounded-full mr-2.5">
                    <img src="https://cdn.tuk.dev/assets/templates/weCare/twitter.png" />
                </div>
                <div class="bg-white p-2 rounded-full mr-2.5">
                    <img src="https://cdn.tuk.dev/assets/templates/weCare/yt.png" />
                </div>
            </div>
        </div>
    </div>
</footer>

// tailwinduikit/wecare/react/components/blue_background_with_yellow_sphere/index.js
const Index = () => (
    <footer>
        <div className="mt-12 relative pt-6">
            <img className="w-8 lg:w-auto absolute inset-0 m-auto mr-12 z-10 -mt-4 lg:-mt-8" src="https://cdn.tuk.dev/assets/templates/weCare/ball-large.png" />
            <img src="https://i.ibb.co/C9d3C0b/footer-bg.png" className="absolute inset-0 w-full h-full object-cover object-center" />
            <div className="container relative z-10 mx-auto lg:flex justify-between px-6 pt-8 lg:pt-32 pb-6 lg:pb-28">
                <div className="lg:w-1/4 pb-12 lg:pb-0">
                    <img className="mb-8" src="https://cdn.tuk.dev/assets/templates/weCare/logo-white.png" alt="logo" />
                    <p className="text-white text-xl">4140 Parker Rd. Allentown, New Mexico 31134</p>
                </div>
                <div className="lg:w-1/2 sm:flex justify-between lg:justify-end">
                    <div className="lg:pr-24 pb-12 lg:pb-0">
                        <h3 className="mb-6 text-lg text-white font-bold">Links</h3>
                        <ul className="text-white">
                            <li className="mb-3">
                                <a href="#">Products</a>
                            </li>
                            <li className="mb-3">
                                <a href="#">Claims</a>
                            </li>
                            <li className="mb-3">
                                <a href="#">Renewals</a>
                            </li>
                            <li>
                                <a href="#">Support</a>
                            </li>
                        </ul>
                    </div>
                    <div className="lg:pr-24 pb-12 lg:pb-0">
                        <h3 className="mb-6 text-lg text-white font-bold">Services</h3>
                        <ul className="text-white">
                            <li className="mb-3">
                                <a href="#">Products</a>
                            </li>
                            <li className="mb-3">
                                <a href="#">Claims</a>
                            </li>
                            <li className="mb-3">
                                <a href="#">Renewals</a>
                            </li>
                            <li>
                                <a href="#">Support</a>
                            </li>
                        </ul>
                    </div>
                    <div>
                        <h3 className="mb-6 text-lg text-white font-bold">About</h3>
                        <ul className="text-white">
                            <li className="mb-3">
                                <a href="#">Products</a>
                            </li>
                            <li className="mb-3">
                                <a href="#">Claims</a>
                            </li>
                            <li className="mb-3">
                                <a href="#">Renewals</a>
                            </li>
                            <li>
                                <a href="#">Support</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div className="lg:w-1/4 flex lg:justify-end items-end mt-12 lg:mt-0">
                    <div className="bg-white p-2 rounded-full mr-2.5">
                        <img src="https://cdn.tuk.dev/assets/templates/weCare/fb.png" />
                    </div>
                    <div className="bg-white p-2 rounded-full mr-2.5">
                        <img src="https://cdn.tuk.dev/assets/templates/weCare/twitter.png" />
                    </div>
                    <div className="bg-white p-2 rounded-full mr-2.5">
                        <img src="https://cdn.tuk.dev/assets/templates/weCare/yt.png" />
                    </div>
                </div>
            </div>
        </div>
    </footer>
);
export default Index;
