// react/components/application-ui/forms/input-groups/input_with_label_and_help_text/index.js
import React from "react";
import ReactDOM from "react-dom";

const Component = (props) => (
<>
<div className="p-8 flex items-center justify-center bg-white">
    <div className="w-full max-w-xs mx-auto">
      
  <div>
    <label htmlFor="email" className="block text-sm font-medium text-gray-700">Email</label>
    <div className="mt-1">
      <input type="text" name="email" id="email" className="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md" placeholder="you@example.com" aria-describedby="email-description">
    </div>
    <p className="mt-2 text-sm text-gray-500" id="email-description">Make your password short and easy to guess.</p>
  </div>

    </div>
  </div>
</>
);

ReactDOM.render(<Component/>, document.getElementById('root'));

// vue/components/application-ui/forms/input-groups/input_with_label_and_help_text.vue
<template>
    <div class="p-8 flex items-center justify-center bg-white">
      <div class="w-full max-w-xs mx-auto">
      
    <div>
      <label for="email" class="block text-sm font-medium text-gray-700">Email</label>
      <div class="mt-1">
        <input type="text" name="email" id="email" class="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md" placeholder="you@example.com" aria-describedby="email-description">
      </div>
      <p class="mt-2 text-sm text-gray-500" id="email-description">Make your password short and easy to guess.</p>
    </div>

      </div>
    </div>
</template>

<script>
export default {
  data: () => ({
	
  })
}
</script>
