// react/components/application-ui/overlays/notifications/with_split_buttons/index.js
import React from "react";
import ReactDOM from "react-dom";

const Component = (props) => (
<>
<div className="bg-gray-100" style={{minHeight: "320px"}}>
    
  <div className="fixed inset-0 flex items-end justify-center px-4 py-6 pointer-events-none sm:p-6 sm:items-start sm:justify-end">
    <div data-todo-x-data="{ show: true }" data-todo-x-show="show" data-todo-x-description="Notification panel, show/hide based on alert state." data-todo-x-transition-enter="transform ease-out duration-300 transition" data-todo-x-transition-enter-start="translate-y-2 opacity-0 sm:translate-y-0 sm:translate-x-2" data-todo-x-transition-enter-end="translate-y-0 opacity-100 sm:translate-x-0" data-todo-x-transition-leave="transition ease-in duration-100" data-todo-x-transition-leave-start="opacity-100" data-todo-x-transition-leave-end="opacity-0" className="max-w-md w-full bg-white shadow-lg rounded-lg pointer-events-auto flex ring-1 ring-black ring-opacity-5 divide-x divide-gray-200">
      <div className="w-0 flex-1 flex items-center p-4">
        <div className="w-full">
          <p className="text-sm font-medium text-gray-900">
            Receive notifications
          </p>
          <p className="mt-1 text-sm text-gray-500">
            Notications may include alerts, sounds, and badges.
          </p>
        </div>
      </div>
      <div className="flex">
        <div className="flex flex-col divide-y divide-gray-200">
          <div className="h-0 flex-1 flex">
            <button data-todo-at-click="show = false; setTimeout(() => show = true, 1000)" className="w-full border border-transparent rounded-none rounded-tr-lg px-4 py-3 flex items-center justify-center text-sm font-medium text-indigo-600 hover:text-indigo-500 focus:outline-none focus:z-10 focus:ring-2 focus:ring-indigo-500">
              Reply
            </button>
          </div>
          <div className="h-0 flex-1 flex">
            <button data-todo-at-click="show = false; setTimeout(() => show = true, 1000)" className="w-full border border-transparent rounded-none rounded-br-lg px-4 py-3 flex items-center justify-center text-sm font-medium text-gray-700 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500">
              Don't allow
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>

  </div>
</>
);

ReactDOM.render(<Component/>, document.getElementById('root'));

// vue/components/application-ui/overlays/notifications/with_split_buttons.vue
<!-- This example requires Tailwind CSS v2.0+ -->
<template>
  <!-- Global notification live region, render this permanently at the end of the document -->
  <div aria-live="assertive" class="fixed inset-0 flex items-end justify-center px-4 py-6 pointer-events-none sm:p-6 sm:items-start sm:justify-end">
    <!-- Notification panel, dynamically insert this into the live region when it needs to be displayed -->
    <transition enter-active-class="transform ease-out duration-300 transition" enter-from-class="translate-y-2 opacity-0 sm:translate-y-0 sm:translate-x-2" enter-to-class="translate-y-0 opacity-100 sm:translate-x-0" leave-active-class="transition ease-in duration-100" leave-from-class="opacity-100" leave-to-class="opacity-0">
      <div v-if="show" class="max-w-md w-full bg-white shadow-lg rounded-lg pointer-events-auto flex ring-1 ring-black ring-opacity-5 divide-x divide-gray-200">
        <div class="w-0 flex-1 flex items-center p-4">
          <div class="w-full">
            <p class="text-sm font-medium text-gray-900">
              Receive notifications
            </p>
            <p class="mt-1 text-sm text-gray-500">
              Notications may include alerts, sounds, and badges.
            </p>
          </div>
        </div>
        <div class="flex">
          <div class="flex flex-col divide-y divide-gray-200">
            <div class="h-0 flex-1 flex">
              <button @click="show = false" class="w-full border border-transparent rounded-none rounded-tr-lg px-4 py-3 flex items-center justify-center text-sm font-medium text-indigo-600 hover:text-indigo-500 focus:outline-none focus:z-10 focus:ring-2 focus:ring-indigo-500">
                Reply
              </button>
            </div>
            <div class="h-0 flex-1 flex">
              <button @click="show = false" class="w-full border border-transparent rounded-none rounded-br-lg px-4 py-3 flex items-center justify-center text-sm font-medium text-gray-700 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500">
                Don't allow
              </button>
            </div>
          </div>
        </div>
      </div>
    </transition>
  </div>
</template>

<script>
import { ref } from 'vue'

export default {
  setup() {
    const show = ref(true)

    return {
      show,
    }
  },
}
</script>
