// tailwinduikit/prodify/vue/src/components/pricing_heading/index.vue
<template>
    <div class="flex flex-col w-full items-center justify-center pt-10 lg:pt-28 f-f-l">
        <h1 class="text-2xl md:text-6xl xl:text-8xl font-black text-center text-color-gradient pb-24 md:leading-tight">
            You get more than what <br />
            you pay for :)
        </h1>
    </div>
</template>

// tailwinduikit/prodify/angular/src/app/components/pricing-heading/pricing-heading.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'app-pricing-heading',
    templateUrl: './pricing-heading.component.html',
    styleUrls: ['./pricing-heading.component.css'],
})
export class PricingHeadingComponent implements OnInit {
    constructor() {}

    ngOnInit(): void {}
}

<div class="flex flex-col w-full items-center justify-center pt-10 lg:pt-28 f-f-l">
    <h1 class="text-2xl md:text-6xl xl:text-8xl font-black text-center text-color-gradient pb-24 md:leading-tight">
        You get more than what <br />
        you pay for :)
    </h1>
</div>
