// react/components/marketing/sections/feature-sections/with_feature_list/index.js
import React from "react";
import ReactDOM from "react-dom";

const Component = (props) => (
<>
<div className="bg-white">
    <div className="max-w-7xl mx-auto py-16 px-4 sm:px-6 lg:py-24 lg:px-8 lg:grid lg:grid-cols-3 lg:gap-x-8">
      <div>
        <h2 className="text-base font-semibold text-indigo-600 uppercase tracking-wide">Everything you need</h2>
        <p className="mt-2 text-3xl font-extrabold text-gray-900">All-in-one platform</p>
        <p className="mt-4 text-lg text-gray-500">Ac euismod vel sit maecenas id pellentesque eu sed consectetur. Malesuada adipiscing sagittis vel nulla nec.</p>
      </div>
      <div className="mt-12 lg:mt-0 lg:col-span-2">
        <dl className="space-y-10 sm:space-y-0 sm:grid sm:grid-cols-2 sm:grid-rows-4 sm:grid-flow-col sm:gap-x-6 sm:gap-y-10 lg:gap-x-8">
          
            <div className="flex">
              <svg className="flex-shrink-0 h-6 w-6 text-green-500" data-todo-x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"></path>
</svg>
              <div className="ml-3">
                <dt className="text-lg leading-6 font-medium text-gray-900">
                  Invite team members
                </dt>
                <dd className="mt-2 text-base text-gray-500">
                  You can manage phone, email and chat conversations all from a single mailbox.
                </dd>
              </div>
            </div>
          
            <div className="flex">
              <svg className="flex-shrink-0 h-6 w-6 text-green-500" data-todo-x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"></path>
</svg>
              <div className="ml-3">
                <dt className="text-lg leading-6 font-medium text-gray-900">
                  List view
                </dt>
                <dd className="mt-2 text-base text-gray-500">
                  You can manage phone, email and chat conversations all from a single mailbox.
                </dd>
              </div>
            </div>
          
            <div className="flex">
              <svg className="flex-shrink-0 h-6 w-6 text-green-500" data-todo-x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"></path>
</svg>
              <div className="ml-3">
                <dt className="text-lg leading-6 font-medium text-gray-900">
                  Keyboard shortcuts
                </dt>
                <dd className="mt-2 text-base text-gray-500">
                  You can manage phone, email and chat conversations all from a single mailbox.
                </dd>
              </div>
            </div>
          
            <div className="flex">
              <svg className="flex-shrink-0 h-6 w-6 text-green-500" data-todo-x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"></path>
</svg>
              <div className="ml-3">
                <dt className="text-lg leading-6 font-medium text-gray-900">
                  Calendars
                </dt>
                <dd className="mt-2 text-base text-gray-500">
                  You can manage phone, email and chat conversations all from a single mailbox.
                </dd>
              </div>
            </div>
          
            <div className="flex">
              <svg className="flex-shrink-0 h-6 w-6 text-green-500" data-todo-x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"></path>
</svg>
              <div className="ml-3">
                <dt className="text-lg leading-6 font-medium text-gray-900">
                  Notifications
                </dt>
                <dd className="mt-2 text-base text-gray-500">
                  Find what you need with advanced filters, bulk actions, and quick views.
                </dd>
              </div>
            </div>
          
            <div className="flex">
              <svg className="flex-shrink-0 h-6 w-6 text-green-500" data-todo-x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"></path>
</svg>
              <div className="ml-3">
                <dt className="text-lg leading-6 font-medium text-gray-900">
                  Boards
                </dt>
                <dd className="mt-2 text-base text-gray-500">
                  Find what you need with advanced filters, bulk actions, and quick views.
                </dd>
              </div>
            </div>
          
            <div className="flex">
              <svg className="flex-shrink-0 h-6 w-6 text-green-500" data-todo-x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"></path>
</svg>
              <div className="ml-3">
                <dt className="text-lg leading-6 font-medium text-gray-900">
                  Reporting
                </dt>
                <dd className="mt-2 text-base text-gray-500">
                  Find what you need with advanced filters, bulk actions, and quick views.
                </dd>
              </div>
            </div>
          
            <div className="flex">
              <svg className="flex-shrink-0 h-6 w-6 text-green-500" data-todo-x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"></path>
</svg>
              <div className="ml-3">
                <dt className="text-lg leading-6 font-medium text-gray-900">
                  Mobile app
                </dt>
                <dd className="mt-2 text-base text-gray-500">
                  Find what you need with advanced filters, bulk actions, and quick views.
                </dd>
              </div>
            </div>
          
        </dl>
      </div>
    </div>
  </div>
</>
);

ReactDOM.render(<Component/>, document.getElementById('root'));

// vue/components/marketing/sections/feature-sections/with_feature_list.vue
<template>
    <div class="bg-white">
      <div class="max-w-7xl mx-auto py-16 px-4 sm:px-6 lg:py-24 lg:px-8 lg:grid lg:grid-cols-3 lg:gap-x-8">
        <div>
          <h2 class="text-base font-semibold text-indigo-600 uppercase tracking-wide">Everything you need</h2>
          <p class="mt-2 text-3xl font-extrabold text-gray-900">All-in-one platform</p>
          <p class="mt-4 text-lg text-gray-500">Ac euismod vel sit maecenas id pellentesque eu sed consectetur. Malesuada adipiscing sagittis vel nulla nec.</p>
        </div>
        <div class="mt-12 lg:mt-0 lg:col-span-2">
          <dl class="space-y-10 sm:space-y-0 sm:grid sm:grid-cols-2 sm:grid-rows-4 sm:grid-flow-col sm:gap-x-6 sm:gap-y-10 lg:gap-x-8">
          
              <div class="flex">
                <svg class="flex-shrink-0 h-6 w-6 text-green-500" x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
  </svg>
                <div class="ml-3">
                  <dt class="text-lg leading-6 font-medium text-gray-900">
                    Invite team members
                  </dt>
                  <dd class="mt-2 text-base text-gray-500">
                    You can manage phone, email and chat conversations all from a single mailbox.
                  </dd>
                </div>
              </div>
          
              <div class="flex">
                <svg class="flex-shrink-0 h-6 w-6 text-green-500" x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
  </svg>
                <div class="ml-3">
                  <dt class="text-lg leading-6 font-medium text-gray-900">
                    List view
                  </dt>
                  <dd class="mt-2 text-base text-gray-500">
                    You can manage phone, email and chat conversations all from a single mailbox.
                  </dd>
                </div>
              </div>
          
              <div class="flex">
                <svg class="flex-shrink-0 h-6 w-6 text-green-500" x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
  </svg>
                <div class="ml-3">
                  <dt class="text-lg leading-6 font-medium text-gray-900">
                    Keyboard shortcuts
                  </dt>
                  <dd class="mt-2 text-base text-gray-500">
                    You can manage phone, email and chat conversations all from a single mailbox.
                  </dd>
                </div>
              </div>
          
              <div class="flex">
                <svg class="flex-shrink-0 h-6 w-6 text-green-500" x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
  </svg>
                <div class="ml-3">
                  <dt class="text-lg leading-6 font-medium text-gray-900">
                    Calendars
                  </dt>
                  <dd class="mt-2 text-base text-gray-500">
                    You can manage phone, email and chat conversations all from a single mailbox.
                  </dd>
                </div>
              </div>
          
              <div class="flex">
                <svg class="flex-shrink-0 h-6 w-6 text-green-500" x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
  </svg>
                <div class="ml-3">
                  <dt class="text-lg leading-6 font-medium text-gray-900">
                    Notifications
                  </dt>
                  <dd class="mt-2 text-base text-gray-500">
                    Find what you need with advanced filters, bulk actions, and quick views.
                  </dd>
                </div>
              </div>
          
              <div class="flex">
                <svg class="flex-shrink-0 h-6 w-6 text-green-500" x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
  </svg>
                <div class="ml-3">
                  <dt class="text-lg leading-6 font-medium text-gray-900">
                    Boards
                  </dt>
                  <dd class="mt-2 text-base text-gray-500">
                    Find what you need with advanced filters, bulk actions, and quick views.
                  </dd>
                </div>
              </div>
          
              <div class="flex">
                <svg class="flex-shrink-0 h-6 w-6 text-green-500" x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
  </svg>
                <div class="ml-3">
                  <dt class="text-lg leading-6 font-medium text-gray-900">
                    Reporting
                  </dt>
                  <dd class="mt-2 text-base text-gray-500">
                    Find what you need with advanced filters, bulk actions, and quick views.
                  </dd>
                </div>
              </div>
          
              <div class="flex">
                <svg class="flex-shrink-0 h-6 w-6 text-green-500" x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
  </svg>
                <div class="ml-3">
                  <dt class="text-lg leading-6 font-medium text-gray-900">
                    Mobile app
                  </dt>
                  <dd class="mt-2 text-base text-gray-500">
                    Find what you need with advanced filters, bulk actions, and quick views.
                  </dd>
                </div>
              </div>
          
          </dl>
        </div>
      </div>
    </div>
</template>

<script>
export default {
  data: () => ({
	
  })
}
</script>
