// vue/components/application-ui/navigation/steps/circles_with_text.vue
<template>
    <div class="bg-white">
      <div class="px-4 flex justify-center sm:px-6 lg:px-8 py-12">
        <div class="min-w-0">
        
    <nav aria-label="Progress">
      <ol class="overflow-hidden">
      
          <li class="relative pb-10">
          
              <!-- Complete Step -->
              <div class="-ml-px absolute mt-0.5 top-4 left-4 w-0.5 h-full bg-indigo-600" aria-hidden="true"></div>
              <a href="#" class="relative flex items-start group">
                <span class="h-9 flex items-center">
                  <span class="relative z-10 w-8 h-8 flex items-center justify-center bg-indigo-600 rounded-full group-hover:bg-indigo-800">
                    <svg class="w-5 h-5 text-white" x-description="Heroicon name: solid/check" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
    <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path>
  </svg>
                  </span>
                </span>
                <span class="ml-4 min-w-0 flex flex-col">
                  <span class="text-xs font-semibold uppercase tracking-wide">Create account</span>
                  <span class="text-sm text-gray-500">Vitae sed mi luctus laoreet.</span>
                </span>
              </a>
            </li>
      
          <li class="relative pb-10">
          
              <!-- Current Step -->
              <div class="-ml-px absolute mt-0.5 top-4 left-4 w-0.5 h-full bg-gray-300" aria-hidden="true"></div>
              <a href="#" class="relative flex items-start group" aria-current="step">
                <span class="h-9 flex items-center" aria-hidden="true">
                  <span class="relative z-10 w-8 h-8 flex items-center justify-center bg-white border-2 border-indigo-600 rounded-full">
                    <span class="h-2.5 w-2.5 bg-indigo-600 rounded-full"></span>
                  </span>
                </span>
                <span class="ml-4 min-w-0 flex flex-col">
                  <span class="text-xs font-semibold uppercase tracking-wide text-indigo-600">Profile information</span>
                  <span class="text-sm text-gray-500">Cursus semper viverra facilisis et et some more.</span>
                </span>
              </a>
            </li>
      
          <li class="relative pb-10">
          
            
                <div class="-ml-px absolute mt-0.5 top-4 left-4 w-0.5 h-full bg-gray-300" aria-hidden="true"></div>
              <a href="#" class="relative flex items-start group">
                <span class="h-9 flex items-center" aria-hidden="true">
                  <span class="relative z-10 w-8 h-8 flex items-center justify-center bg-white border-2 border-gray-300 rounded-full group-hover:border-gray-400">
                    <span class="h-2.5 w-2.5 bg-transparent rounded-full group-hover:bg-gray-300"></span>
                  </span>
                </span>
                <span class="ml-4 min-w-0 flex flex-col">
                  <span class="text-xs font-semibold uppercase tracking-wide text-gray-500">Business information</span>
                  <span class="text-sm text-gray-500">Penatibus eu quis ante.</span>
                </span>
              </a>
            </li>
      
          <li class="relative pb-10">
          
            
                <div class="-ml-px absolute mt-0.5 top-4 left-4 w-0.5 h-full bg-gray-300" aria-hidden="true"></div>
              <a href="#" class="relative flex items-start group">
                <span class="h-9 flex items-center" aria-hidden="true">
                  <span class="relative z-10 w-8 h-8 flex items-center justify-center bg-white border-2 border-gray-300 rounded-full group-hover:border-gray-400">
                    <span class="h-2.5 w-2.5 bg-transparent rounded-full group-hover:bg-gray-300"></span>
                  </span>
                </span>
                <span class="ml-4 min-w-0 flex flex-col">
                  <span class="text-xs font-semibold uppercase tracking-wide text-gray-500">Theme</span>
                  <span class="text-sm text-gray-500">Faucibus nec enim leo et.</span>
                </span>
              </a>
            </li>
      
          <li class="relative ">
          
              <a href="#" class="relative flex items-start group">
                <span class="h-9 flex items-center" aria-hidden="true">
                  <span class="relative z-10 w-8 h-8 flex items-center justify-center bg-white border-2 border-gray-300 rounded-full group-hover:border-gray-400">
                    <span class="h-2.5 w-2.5 bg-transparent rounded-full group-hover:bg-gray-300"></span>
                  </span>
                </span>
                <span class="ml-4 min-w-0 flex flex-col">
                  <span class="text-xs font-semibold uppercase tracking-wide text-gray-500">Preview</span>
                  <span class="text-sm text-gray-500">Iusto et officia maiores porro ad non quas.</span>
                </span>
              </a>
            </li>
      
      </ol>
    </nav>

        </div>
      </div>
    </div>
</template>

<script>
export default {
  data: () => ({
	
  })
}
</script>

// react/components/application-ui/navigation/steps/circles_with_text/index.js
import React from "react";
import ReactDOM from "react-dom";

const Component = (props) => (
<>
<div className="bg-white">
    <div className="px-4 flex justify-center sm:px-6 lg:px-8 py-12">
      <div className="min-w-0">
        
  <nav aria-label="Progress">
    <ol className="overflow-hidden">
      
        <li className="relative pb-10">
          
            {/* Complete Step */}
            <div className="-ml-px absolute mt-0.5 top-4 left-4 w-0.5 h-full bg-indigo-600" aria-hidden="true"></div>
            <a href="/" className="relative flex items-start group">
              <span className="h-9 flex items-center">
                <span className="relative z-10 w-8 h-8 flex items-center justify-center bg-indigo-600 rounded-full group-hover:bg-indigo-800">
                  <svg className="w-5 h-5 text-white" data-todo-x-description="Heroicon name: solid/check" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
  <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd"></path>
</svg>
                </span>
              </span>
              <span className="ml-4 min-w-0 flex flex-col">
                <span className="text-xs font-semibold uppercase tracking-wide">Create account</span>
                <span className="text-sm text-gray-500">Vitae sed mi luctus laoreet.</span>
              </span>
            </a>
          </li>
      
        <li className="relative pb-10">
          
            {/* Current Step */}
            <div className="-ml-px absolute mt-0.5 top-4 left-4 w-0.5 h-full bg-gray-300" aria-hidden="true"></div>
            <a href="/" className="relative flex items-start group" aria-current="step">
              <span className="h-9 flex items-center" aria-hidden="true">
                <span className="relative z-10 w-8 h-8 flex items-center justify-center bg-white border-2 border-indigo-600 rounded-full">
                  <span className="h-2.5 w-2.5 bg-indigo-600 rounded-full"></span>
                </span>
              </span>
              <span className="ml-4 min-w-0 flex flex-col">
                <span className="text-xs font-semibold uppercase tracking-wide text-indigo-600">Profile information</span>
                <span className="text-sm text-gray-500">Cursus semper viverra facilisis et et some more.</span>
              </span>
            </a>
          </li>
      
        <li className="relative pb-10">
          
            
              <div className="-ml-px absolute mt-0.5 top-4 left-4 w-0.5 h-full bg-gray-300" aria-hidden="true"></div>
            <a href="/" className="relative flex items-start group">
              <span className="h-9 flex items-center" aria-hidden="true">
                <span className="relative z-10 w-8 h-8 flex items-center justify-center bg-white border-2 border-gray-300 rounded-full group-hover:border-gray-400">
                  <span className="h-2.5 w-2.5 bg-transparent rounded-full group-hover:bg-gray-300"></span>
                </span>
              </span>
              <span className="ml-4 min-w-0 flex flex-col">
                <span className="text-xs font-semibold uppercase tracking-wide text-gray-500">Business information</span>
                <span className="text-sm text-gray-500">Penatibus eu quis ante.</span>
              </span>
            </a>
          </li>
      
        <li className="relative pb-10">
          
            
              <div className="-ml-px absolute mt-0.5 top-4 left-4 w-0.5 h-full bg-gray-300" aria-hidden="true"></div>
            <a href="/" className="relative flex items-start group">
              <span className="h-9 flex items-center" aria-hidden="true">
                <span className="relative z-10 w-8 h-8 flex items-center justify-center bg-white border-2 border-gray-300 rounded-full group-hover:border-gray-400">
                  <span className="h-2.5 w-2.5 bg-transparent rounded-full group-hover:bg-gray-300"></span>
                </span>
              </span>
              <span className="ml-4 min-w-0 flex flex-col">
                <span className="text-xs font-semibold uppercase tracking-wide text-gray-500">Theme</span>
                <span className="text-sm text-gray-500">Faucibus nec enim leo et.</span>
              </span>
            </a>
          </li>
      
        <li className="relative ">
          
            <a href="/" className="relative flex items-start group">
              <span className="h-9 flex items-center" aria-hidden="true">
                <span className="relative z-10 w-8 h-8 flex items-center justify-center bg-white border-2 border-gray-300 rounded-full group-hover:border-gray-400">
                  <span className="h-2.5 w-2.5 bg-transparent rounded-full group-hover:bg-gray-300"></span>
                </span>
              </span>
              <span className="ml-4 min-w-0 flex flex-col">
                <span className="text-xs font-semibold uppercase tracking-wide text-gray-500">Preview</span>
                <span className="text-sm text-gray-500">Iusto et officia maiores porro ad non quas.</span>
              </span>
            </a>
          </li>
      
    </ol>
  </nav>

      </div>
    </div>
  </div>
</>
);

ReactDOM.render(<Component/>, document.getElementById('root'));
