// tailwinduikit/todo-webapp/angular/src/app/components/sidebar/sidebar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
@Component({
    selector: 'app-sidebar',
    templateUrl: './sidebar.component.html',
})
export class SidebarComponent implements OnInit {
    active: string = '';
    constructor(private router: Router) {
        this.active = router.url;
    }
    public openSidebar = (flag) => {
        let sidebar = document.getElementById('sidebar');
        flag ? sidebar.classList.add('hidden') : sidebar.classList.remove('hidden');
    };
    ngOnInit(): void {}
}

<!-- Navbar Ends -->
<div (click)="openSidebar(false)" class="flex items-center justify-center rounded-r-md bg-gray-800 text-gray-300 ml-0 cursor-pointer absolute inset-0 mt-10 m-auto w-8 h-8">
    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevron-right" width="28" height="28" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
        <path stroke="none" d="M0 0h24v24H0z" />
        <polyline points="9 6 15 12 9 18" />
    </svg>
</div>
<div id="sidebar" class="overflow-y-scroll lg:overflow-y-auto fixed lg:sticky h-screen lg:h-auto z-40 top-0 bg-gray-900 pt-10 w-64 lg:w-72">
    <div class="px-8">
        <div class="flex items-center justify-between">
            <div class="w-32">
                <img class="w-full" src="https://cdn.tuk.dev/assets/components/todos/logo.png" alt="quicklist logo" />
            </div>
            <div (click)="openSidebar(true)" class="text-gray-700 ml-8 cursor-pointer">
                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevron-left" width="32" height="32" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" />
                    <polyline points="15 6 9 12 15 18" />
                </svg>
            </div>
        </div>
        <ul class="my-10 flex flex-wrap">
            <li class="w-1/2 flex justify-start mb-6">
                <a href="/" [ngClass]="active == '/' ? 'bg-gray-700 rounded-md text-gray-300 flex flex-col justify-center items-center w-20 h-20 p-4' : 'bg-transparent rounded-md text-gray-600 flex flex-col justify-center items-center w-20 h-20 p-4'">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-layout-kanban" width="28" height="28" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" />
                        <line x1="4" y1="4" x2="10" y2="4" />
                        <line x1="14" y1="4" x2="20" y2="4" />
                        <rect x="4" y="8" width="6" height="12" rx="2" />
                        <rect x="14" y="8" width="6" height="6" rx="2" />
                    </svg>
                    <p class="mt-1 uppercase font-semibold text-xs">kanban</p>
                </a>
            </li>
            <li class="w-1/2 flex justify-end mb-6">
                <a href="/inbox" [ngClass]="active == '/inbox' ? 'bg-gray-700 rounded-md text-gray-300 flex flex-col justify-center items-center w-20 h-20 p-4' : 'bg-transparent rounded-md text-gray-600 flex flex-col justify-center items-center w-20 h-20 p-4'">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-inbox" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" />
                        <rect x="4" y="4" width="16" height="16" rx="2" />
                        <path d="M4 13h3l3 3h4l3 -3h3" />
                    </svg>
                    <p class="mt-1 uppercase font-semibold text-xs">inbox</p>
                </a>
            </li>
            <li class="w-1/2 flex justify-start mb-6">
                <a href="/notebook" [ngClass]="active.indexOf('notebook') !== -1 ? 'bg-gray-700 rounded-md text-gray-300 flex flex-col justify-center items-center w-20 h-20 p-4' : 'bg-transparent rounded-md text-gray-600 flex flex-col justify-center items-center w-20 h-20 p-4'">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-notebook" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" />
                        <path d="M6 4h11a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-11a1 1 0 0 1 -1 -1v-14a1 1 0 0 1 1 -1m3 0v18" />
                        <line x1="13" y1="8" x2="15" y2="8" />
                        <line x1="13" y1="12" x2="15" y2="12" />
                    </svg>
                    <p class="mt-1 uppercase font-semibold text-xs">notebook</p>
                </a>
            </li>
            <li class="w-1/2 flex justify-end mb-6">
                <a href="/calendar-month-view" [ngClass]="active.indexOf('calendar') !== -1 ? 'bg-gray-700 rounded-md text-gray-300 flex flex-col justify-center items-center w-20 h-20 p-4' : 'bg-transparent rounded-md text-gray-600 flex flex-col justify-center items-center w-20 h-20 p-4'">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-calendar-event" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" />
                        <rect x="4" y="5" width="16" height="16" rx="2" />
                        <line x1="16" y1="3" x2="16" y2="7" />
                        <line x1="8" y1="3" x2="8" y2="7" />
                        <line x1="4" y1="11" x2="20" y2="11" />
                        <rect x="8" y="15" width="2" height="2" />
                    </svg>
                    <p class="mt-1 uppercase font-semibold text-xs">calendar</p>
                </a>
            </li>
            <li class="w-1/2 flex justify-start">
                <a href="/important" [ngClass]="active == '/important' ? 'bg-gray-700 rounded-md text-gray-300 flex flex-col justify-center items-center w-20 h-20 p-4' : 'bg-transparent rounded-md text-gray-600 flex flex-col justify-center items-center w-20 h-20 p-4'">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-star" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" />
                        <path d="M12 17.75l-6.172 3.245 1.179-6.873-4.993-4.867 6.9-1.002L12 2l3.086 6.253 6.9 1.002-4.993 4.867 1.179 6.873z" />
                    </svg>
                    <p class="mt-1 uppercase font-semibold text-xs">important</p>
                </a>
            </li>
            <li class="w-1/2 flex justify-end">
                <a href="/projects" [ngClass]="active.indexOf('project') !== -1 ? 'bg-gray-700 rounded-md text-gray-300 flex flex-col justify-center items-center w-20 h-20 p-4' : 'bg-transparent rounded-md text-gray-600 flex flex-col justify-center items-center w-20 h-20 p-4'">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-stack" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" />
                        <polyline points="12 4 4 8 12 12 20 8 12 4" />
                        <polyline points="4 12 12 16 20 12" />
                        <polyline points="4 16 12 20 20 16" />
                    </svg>
                    <p class="mt-1 uppercase font-semibold text-xs">projects</p>
                </a>
            </li>
        </ul>
        <div class="flex items-center justify-between text-gray-600">
            <h4 class="uppercase font-semibold">List</h4>
            <svg xmlns="http://www.w3.org/2000/svg" class="cursor-pointer icon icon-tabler icon-tabler-plus" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" />
                <line x1="12" y1="5" x2="12" y2="19" />
                <line x1="5" y1="12" x2="19" y2="12" />
            </svg>
        </div>
        <ul class="text-gray-600 mt-8">
            <li class="mb-5">Grocery Items</li>
            <li class="mb-5">Family</li>
            <li>Friends</li>
        </ul>
        <div class="my-20">
            <div class="flex items-center justify-between text-gray-600">
                <h4 class="uppercase font-semibold">Labels</h4>
                <svg xmlns="http://www.w3.org/2000/svg" class="cursor-pointer icon icon-tabler icon-tabler-plus" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" />
                    <line x1="12" y1="5" x2="12" y2="19" />
                    <line x1="5" y1="12" x2="19" y2="12" />
                </svg>
            </div>
            <ul class="text-gray-600 mt-8">
                <li class="mb-5 flex items-center">
                    <span class="mr-2 w-2 h-2 rounded-full bg-indigo-600"></span>
                    Work Related
                </li>
                <li class="mb-5 flex items-center">
                    <span class="mr-2 w-2 h-2 rounded-full bg-yellow-600"></span>
                    Family
                </li>
                <li class="mb-5 flex items-center">
                    <span class="mr-2 w-2 h-2 rounded-full bg-green-500"></span>
                    Friends
                </li>
                <li class="mb-5 flex items-center">
                    <span class="mr-2 w-2 h-2 rounded-full bg-purple-600"></span>
                    Grocery
                </li>
                <li class="mb-5 flex items-center">
                    <span class="mr-2 w-2 h-2 rounded-full bg-blue-600"></span>
                    Utilities
                </li>
                <li class="mb-5 flex items-center">
                    <span class="mr-2 w-2 h-2 rounded-full bg-pink-600"></span>
                    Rental
                </li>
                <li class="mb-5 flex items-center">
                    <span class="mr-2 w-2 h-2 rounded-full bg-red-600"></span>
                    Maintenance
                </li>
            </ul>
        </div>
    </div>
    <div class="px-8 py-4 w-full border-t border-gray-800 flex items-center text-gray-600 uppercase text-xs">
        <svg xmlns="http://www.w3.org/2000/svg" class="cursor-pointer icon icon-tabler icon-tabler-trash" width="18" height="18" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" />
            <line x1="4" y1="7" x2="20" y2="7" />
            <line x1="10" y1="11" x2="10" y2="17" />
            <line x1="14" y1="11" x2="14" y2="17" />
            <path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12" />
            <path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3" />
        </svg>
        <p class="cursor-pointer pl-2">trash</p>
    </div>
</div>
<!-- Navbar Ends -->

// tailwinduikit/Eventex/react/components/sidebar.js
import React, { useState, useEffect } from "react";
import Router from "next/router";
export default function Home() {
    const [sidebar, Setsidebar] = useState(false);
    const [sidebarMobile, SetsidebarMobile] = useState(false);
    const [query, setQuery] = useState("");
    useEffect(() => {
        if (Router.router.asPath) {
            const item = Router.router.asPath;
            setQuery(item);
        }
    }, [Router]);
    const checkActive = () => {
        if (query.indexOf("events") !== -1) {
            return "events";
        } else if (query.indexOf("sales") !== -1) {
            return "sales";
        } else if (query.indexOf("analytics") !== -1) {
            return "analytics";
        } else if (query.indexOf("calender-month-view") !== -1) {
            return "calender-month-view";
        }
        return "events";
    };
    return (
        <>
            <div onClick={() => SetsidebarMobile(!sidebarMobile)} className="flex items-center justify-center rounded-r-md bg-gray-800 ml-0 cursor-pointer absolute inset-0 mt-4 md:mt-6 m-auto w-8 h-8 lg:hidden">
                <svg xmlns="http://www.w3.org/2000/svg" width={20} height={20} viewBox="0 0 20 20" fill="none">
                    <path d="M3.33337 6.66667H16.6667" stroke="#A0AEC0" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                    <path d="M3.33337 13.3332H16.6667" stroke="#A0AEC0" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                </svg>
            </div>

            <div onClick={() => Setsidebar(!sidebar)} className="flex items-center justify-center rounded-r-md bg-gray-800 ml-0 cursor-pointer absolute inset-0 mt-4 md:mt-6 m-auto w-8 h-8 hidden lg:block">
                <svg className="m-auto mt-1" xmlns="http://www.w3.org/2000/svg" width={20} height={20} viewBox="0 0 20 20" fill="none">
                    <path d="M3.33337 6.66667H16.6667" stroke="#A0AEC0" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                    <path d="M3.33337 13.3332H16.6667" stroke="#A0AEC0" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                </svg>
            </div>

            <div className="hidden lg:block">
                <div className={sidebar ? "hidden" : "overflow-y-scroll lg:overflow-y-auto fixed lg:sticky h-screen lg:min-h-screen z-40 top-0 bg-gray-800 pt-7 w-64"}>
                    <div className="px-7">
                        <div className="flex items-center justify-between">
                            <div className="w-32">
                                <img className="w-full" src="https://cdn.tuk.dev/assets/templates/virtual-event-management/logo.png" alt="logo" />
                            </div>
                            <div onClick={() => Setsidebar(!sidebar)} className="text-gray-700 ml-8 cursor-pointer">
                                <svg xmlns="http://www.w3.org/2000/svg" width={20} height={20} viewBox="0 0 20 20" fill="none">
                                    <path d="M3.33337 6.66667H16.6667" stroke="#A0AEC0" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                                    <path d="M3.33337 13.3332H16.6667" stroke="#A0AEC0" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                                </svg>
                            </div>
                        </div>
                        <div className="mt-16">
                            <a href="/events">
                                <div className={checkActive() === "events" ? "flex items-center cursor-pointer font-normal text-sm text-red-400 duration-150 ease-in" : "flex items-center cursor-pointer font-normal text-sm text-gray hover:text-red-400 duration-150 ease-in"}>
                                    <div className={checkActive() === "events" ? "px-1 py-1 rounded-sm bg-red-400" : "px-1 py-1 rounded-sm hover:bg-red-400"}>
                                        <svg xmlns="http://www.w3.org/2000/svg" width={20} height={20} viewBox="0 0 20 20" fill="none">
                                            <rect x="3.33337" y="3.3335" width={5} height="13.3333" rx="1.66667" stroke="white" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                                            <rect x="11.6666" y="3.3335" width={5} height="8.33333" rx="1.66667" stroke="white" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                                        </svg>
                                    </div>
                                    <p className="ml-2">Events</p>
                                </div>
                            </a>
                            <a href="/sales">
                                <div className={checkActive() === "sales" ? "flex items-center cursor-pointer font-normal text-sm text-red-400 duration-150 ease-in mt-5" : "flex items-center cursor-pointer font-normal text-sm text-gray hover:text-red-400 duration-150 ease-in mt-5"}>
                                    <div className={checkActive() === "sales" ? "px-1 py-1 rounded-sm bg-red-400" : "px-1 py-1 rounded-sm hover:bg-red-400"}>
                                        <svg xmlns="http://www.w3.org/2000/svg" width={20} height={20} viewBox="0 0 20 20" fill="none">
                                            <path d="M12.5 4.1665V5.83317" stroke="#CBD5E0" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                                            <path d="M12.5 9.1665V10.8332" stroke="#CBD5E0" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                                            <path d="M12.5 14.1665V15.8332" stroke="#CBD5E0" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                                            <path d="M4.16667 4.1665H15.8333C16.7538 4.1665 17.5 4.9127 17.5 5.83317V8.33317C16.5795 8.33317 15.8333 9.07936 15.8333 9.99984C15.8333 10.9203 16.5795 11.6665 17.5 11.6665V14.1665C17.5 15.087 16.7538 15.8332 15.8333 15.8332H4.16667C3.24619 15.8332 2.5 15.087 2.5 14.1665V11.6665C3.42047 11.6665 4.16667 10.9203 4.16667 9.99984C4.16667 9.07936 3.42047 8.33317 2.5 8.33317V5.83317C2.5 4.9127 3.24619 4.1665 4.16667 4.1665" stroke="#CBD5E0" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                                        </svg>
                                    </div>
                                    <p className="ml-2">Sales</p>
                                </div>
                            </a>
                            <a href="./analytics">
                                <div className={checkActive() === "analytics" ? "flex items-center cursor-pointer font-normal text-sm text-red-400 duration-150 ease-in mt-5" : "flex items-center cursor-pointer font-normal text-sm text-gray hover:text-red-400 duration-150 ease-in mt-5"}>
                                    <div className={checkActive() === "analytics" ? "px-1 py-1 rounded-sm bg-red-400" : "px-1 py-1 rounded-sm hover:bg-red-400"}>
                                        <svg xmlns="http://www.w3.org/2000/svg" width={20} height={20} viewBox="0 0 20 20" fill="none">
                                            <path d="M3.33337 15.8337H16.6667" stroke="#CBD5E0" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                                            <path d="M3.33337 12.5L6.66671 7.5L10 9.16667L13.3334 5L16.6667 8.33333" stroke="#CBD5E0" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                                        </svg>
                                    </div>
                                    <p className="ml-2">Analytics</p>
                                </div>
                            </a>
                            <a href="/calender-month-view">
                                <div className={checkActive() === "calender-month-view" ? "flex items-center cursor-pointer font-normal text-sm text-red-400 duration-150 ease-in mt-5" : "flex items-center cursor-pointer font-normal text-sm text-gray hover:text-red-400 duration-150 ease-in mt-5"}>
                                    <div className={checkActive() === "calender-month-view" ? "px-1 py-1 rounded-sm bg-red-400" : "px-1 py-1 rounded-sm hover:bg-red-400"}>
                                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20" fill="none">
                                            <rect x="3.33337" y="4.16699" width="13.3333" height="13.3333" rx="1.66667" stroke="#CBD5E0" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                                            <path d="M13.3333 2.5V5.83333" stroke="#CBD5E0" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                                            <path d="M6.66667 2.5V5.83333" stroke="#CBD5E0" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                                            <path d="M3.33337 9.16667H16.6667" stroke="#CBD5E0" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                                            <rect x="6.66663" y="12.5" width="1.66667" height="1.66667" stroke="#CBD5E0" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                                        </svg>
                                    </div>
                                    <p className="ml-2">Calendar</p>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>

            <div className="lg:hidden">
                <div className={sidebarMobile ? "overflow-y-scroll lg:overflow-y-auto fixed lg:sticky h-screen lg:min-h-screen z-40 top-0 bg-gray-800 pt-7 w-64" : "hidden"}>
                    <div className="px-7">
                        <div className="flex items-center justify-between">
                            <div className="w-32">
                                <img className="w-full" src="https://cdn.tuk.dev/assets/templates/virtual-event-management/logo.png" alt="logo" />
                            </div>
                            <div onClick={() => Setsidebar(!sidebar)} className="text-gray-700 ml-8 cursor-pointer">
                                <svg xmlns="http://www.w3.org/2000/svg" width={20} height={20} viewBox="0 0 20 20" fill="none">
                                    <path d="M3.33337 6.66667H16.6667" stroke="#A0AEC0" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                                    <path d="M3.33337 13.3332H16.6667" stroke="#A0AEC0" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                                </svg>
                            </div>
                        </div>
                        <div className="mt-16">
                            <a href="/events">
                                <div className={checkActive() === "events" ? "flex items-center cursor-pointer font-normal text-sm text-red-400 duration-150 ease-in" : "flex items-center cursor-pointer font-normal text-sm text-gray hover:text-red-400 duration-150 ease-in"}>
                                    <div className={checkActive() === "events" ? "px-1 py-1 rounded-sm bg-red-400" : "px-1 py-1 rounded-sm hover:bg-red-400"}>
                                        <svg xmlns="http://www.w3.org/2000/svg" width={20} height={20} viewBox="0 0 20 20" fill="none">
                                            <rect x="3.33337" y="3.3335" width={5} height="13.3333" rx="1.66667" stroke="white" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                                            <rect x="11.6666" y="3.3335" width={5} height="8.33333" rx="1.66667" stroke="white" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                                        </svg>
                                    </div>
                                    <p className="ml-2">Events</p>
                                </div>
                            </a>
                            <a href="/sales">
                                <div className={checkActive() === "sales" ? "flex items-center cursor-pointer font-normal text-sm text-red-400 duration-150 ease-in mt-5" : "flex items-center cursor-pointer font-normal text-sm text-gray hover:text-red-400 duration-150 ease-in mt-5"}>
                                    <div className={checkActive() === "sales" ? "px-1 py-1 rounded-sm bg-red-400" : "px-1 py-1 rounded-sm hover:bg-red-400"}>
                                        <svg xmlns="http://www.w3.org/2000/svg" width={20} height={20} viewBox="0 0 20 20" fill="none">
                                            <path d="M12.5 4.1665V5.83317" stroke="#CBD5E0" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                                            <path d="M12.5 9.1665V10.8332" stroke="#CBD5E0" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                                            <path d="M12.5 14.1665V15.8332" stroke="#CBD5E0" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                                            <path d="M4.16667 4.1665H15.8333C16.7538 4.1665 17.5 4.9127 17.5 5.83317V8.33317C16.5795 8.33317 15.8333 9.07936 15.8333 9.99984C15.8333 10.9203 16.5795 11.6665 17.5 11.6665V14.1665C17.5 15.087 16.7538 15.8332 15.8333 15.8332H4.16667C3.24619 15.8332 2.5 15.087 2.5 14.1665V11.6665C3.42047 11.6665 4.16667 10.9203 4.16667 9.99984C4.16667 9.07936 3.42047 8.33317 2.5 8.33317V5.83317C2.5 4.9127 3.24619 4.1665 4.16667 4.1665" stroke="#CBD5E0" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                                        </svg>
                                    </div>
                                    <p className="ml-2">Sales</p>
                                </div>
                            </a>
                            <a href="./analytics">
                                <div className={checkActive() === "analytics" ? "flex items-center cursor-pointer font-normal text-sm text-red-400 duration-150 ease-in mt-5" : "flex items-center cursor-pointer font-normal text-sm text-gray hover:text-red-400 duration-150 ease-in mt-5"}>
                                    <div className={checkActive() === "analytics" ? "px-1 py-1 rounded-sm bg-red-400" : "px-1 py-1 rounded-sm hover:bg-red-400"}>
                                        <svg xmlns="http://www.w3.org/2000/svg" width={20} height={20} viewBox="0 0 20 20" fill="none">
                                            <path d="M3.33337 15.8337H16.6667" stroke="#CBD5E0" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                                            <path d="M3.33337 12.5L6.66671 7.5L10 9.16667L13.3334 5L16.6667 8.33333" stroke="#CBD5E0" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                                        </svg>
                                    </div>
                                    <p className="ml-2">Analytics</p>
                                </div>
                            </a>
                            <a href="/calender-month-view">
                                <div className={checkActive() === "calender-month-view" ? "flex items-center cursor-pointer font-normal text-sm text-red-400 duration-150 ease-in mt-5" : "flex items-center cursor-pointer font-normal text-sm text-gray hover:text-red-400 duration-150 ease-in mt-5"}>
                                    <div className={checkActive() === "calender-month-view" ? "px-1 py-1 rounded-sm bg-red-400" : "px-1 py-1 rounded-sm hover:bg-red-400"}>
                                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20" fill="none">
                                            <rect x="3.33337" y="4.16699" width="13.3333" height="13.3333" rx="1.66667" stroke="#CBD5E0" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                                            <path d="M13.3333 2.5V5.83333" stroke="#CBD5E0" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                                            <path d="M6.66667 2.5V5.83333" stroke="#CBD5E0" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                                            <path d="M3.33337 9.16667H16.6667" stroke="#CBD5E0" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                                            <rect x="6.66663" y="12.5" width="1.66667" height="1.66667" stroke="#CBD5E0" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
                                        </svg>
                                    </div>
                                    <p className="ml-2">Calendar</p>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
}
