// react/components/application-ui/forms/select-menus/custom_with_status_indicator/index.js
import React from "react";
import ReactDOM from "react-dom";

const Component = (props) => (
<>
<div className="p-8 flex justify-center bg-gray-100" style={{minHeight: "600px"}}>
    <div className="w-full max-w-xs mx-auto">
      
  <!--
  Custom select controls like this require a considerable amount of JS to implement from scratch. We're planning
  to build some low-level libraries to make this easier with popular frameworks like React, Vue, and even Alpine.js
  in the near future, but in the mean time we recommend these reference guides when building your implementation:

  https://www.w3.org/TR/wai-aria-practices/#Listbox
  https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html
-->
  <div data-todo-x-data="Components.customSelect({ open: true, value: 3, selected: 3 })" data-todo-x-init="init()">
    <label id="listbox-label" className="block text-sm font-medium text-gray-700">
      Assigned to
    </label>
    <div className="mt-1 relative">
      <button type="button" data-todo-x-ref="button" data-todo-at-keydown-arrow-up-stop-prevent="onButtonClick()" data-todo-at-keydown-arrow-down-stop-prevent="onButtonClick()" data-todo-at-click="onButtonClick()" aria-haspopup="listbox" data-todo-colon-aria-expanded="open" aria-expanded="true" aria-labelledby="listbox-label" className="relative w-full bg-white border border-gray-300 rounded-md shadow-sm pl-3 pr-10 py-2 text-left cursor-default focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
        <div className="flex items-center">
          <span aria-label="Online" data-todo-colon-aria-label="[true,false,false,true,false,true,true,false,true,false][value] ? 'Online' : 'Offline'" :className="{ 'bg-green-400': [true,false,false,true,false,true,true,false,true,false][value], 'bg-gray-200': !([true,false,false,true,false,true,true,false,true,false][value])}" className="bg-green-400 flex-shrink-0 inline-block h-2 w-2 rounded-full"></span>
          <span data-todo-x-text="[&quot;Wade Cooper&quot;,&quot;Arlene Mccoy&quot;,&quot;Devon Webb&quot;,&quot;Tom Cook&quot;,&quot;Tanya Fox&quot;,&quot;Hellen Schmidt&quot;,&quot;Caroline Schultz&quot;,&quot;Mason Heaney&quot;,&quot;Claudie Smitham&quot;,&quot;Emil Schaefer&quot;][value]" className="ml-3 block truncate">
            Tom Cook
          </span>
        </div>
        <span className="absolute inset-y-0 right-0 flex items-center pr-2 pointer-events-none">
          <svg className="h-5 w-5 text-gray-400" data-todo-x-description="Heroicon name: selector" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
  <path fillRule="evenodd" d="M10 3a1 1 0 01.707.293l3 3a1 1 0 01-1.414 1.414L10 5.414 7.707 7.707a1 1 0 01-1.414-1.414l3-3A1 1 0 0110 3zm-3.707 9.293a1 1 0 011.414 0L10 14.586l2.293-2.293a1 1 0 011.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z" clipRule="evenodd"></path>
</svg>
        </span>
      </button>

      <div data-todo-x-show="open" data-todo-at-click-away="open = false" data-todo-x-description="Select popover, show/hide based on select state." data-todo-x-transition-leave="transition ease-in duration-100" data-todo-x-transition-leave-start="opacity-100" data-todo-x-transition-leave-end="opacity-0" className="absolute mt-1 w-full rounded-md bg-white shadow-lg">
        <ul data-todo-at-keydown-enter-stop-prevent="onOptionSelect()" data-todo-at-keydown-space-stop-prevent="onOptionSelect()" data-todo-at-keydown-escape="onEscape()" data-todo-at-keydown-arrow-up-prevent="onArrowUp()" data-todo-at-keydown-arrow-down-prevent="onArrowDown()" data-todo-x-ref="listbox" tabIndex={-1} role="listbox" aria-labelledby="listbox-label" data-todo-colon-aria-activedescendant="activeDescendant" aria-activedescendant="listbox-item-3" className="max-h-60 rounded-md py-1 text-base ring-1 ring-black ring-opacity-5 overflow-auto focus:outline-none sm:text-sm" data-todo-x-max="1">
          
            <li data-todo-x-description="Select option, manage highlight styles based on mouseenter/mouseleave and keyboard navigation." data-todo-x-state-on="Highlighted" data-todo-x-state-off="Not Highlighted" id="listbox-item-0" role="option" data-todo-at-click="choose(0)" data-todo-at-mouseenter="selected = 0" data-todo-at-mouseleave="selected = null" data-todo-colon-className="{ 'text-white bg-indigo-600': selected === 0, 'text-gray-900': !(selected === 0) }" className="text-gray-900 cursor-default select-none relative py-2 pl-3 pr-9">
              <div className="flex items-center">
                <span data-todo-x-state-on="Online" data-todo-x-state-off="Not Online" data-todo-colon-className="{ 'bg-green-400': [true,false,false,true,false,true,true,false,true,false][0], 'bg-gray-200': !([true,false,false,true,false,true,true,false,true,false][0])}" className="bg-green-400 flex-shrink-0 inline-block h-2 w-2 rounded-full" aria-hidden="true"></span>
                <span data-todo-x-state-on="Selected" data-todo-x-state-off="Not Selected" data-todo-colon-className="{ 'font-semibold': value === 0, 'font-normal': !(value === 0) }" className="ml-3 font-normal block truncate">
                  Wade Cooper
                  <span className="sr-only"> is online</span>
                </span>
              </div>

              <span data-todo-x-description="Checkmark, only display for selected option." data-todo-x-state-on="Highlighted" data-todo-x-state-off="Not Highlighted" data-todo-x-show="value === 0" data-todo-colon-className="{ 'text-white': selected === 0, 'text-indigo-600': !(selected === 0) }" className="absolute inset-y-0 right-0 flex items-center pr-4">
                <svg className="h-5 w-5" data-todo-x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
  <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd"></path>
</svg>
              </span>
            </li>
          
            <li data-todo-x-description="Select option, manage highlight styles based on mouseenter/mouseleave and keyboard navigation." data-todo-x-state-on="Highlighted" data-todo-x-state-off="Not Highlighted" id="listbox-item-1" role="option" data-todo-at-click="choose(1)" data-todo-at-mouseenter="selected = 1" data-todo-at-mouseleave="selected = null" data-todo-colon-className="{ 'text-white bg-indigo-600': selected === 1, 'text-gray-900': !(selected === 1) }" className="text-gray-900 cursor-default select-none relative py-2 pl-3 pr-9">
              <div className="flex items-center">
                <span data-todo-x-state-on="Online" data-todo-x-state-off="Not Online" data-todo-colon-className="{ 'bg-green-400': [true,false,false,true,false,true,true,false,true,false][1], 'bg-gray-200': !([true,false,false,true,false,true,true,false,true,false][1])}" className="bg-gray-200 flex-shrink-0 inline-block h-2 w-2 rounded-full" aria-hidden="true"></span>
                <span data-todo-x-state-on="Selected" data-todo-x-state-off="Not Selected" data-todo-colon-className="{ 'font-semibold': value === 1, 'font-normal': !(value === 1) }" className="ml-3 font-normal block truncate">
                  Arlene Mccoy
                  <span className="sr-only"> is offline</span>
                </span>
              </div>

              <span data-todo-x-description="Checkmark, only display for selected option." data-todo-x-state-on="Highlighted" data-todo-x-state-off="Not Highlighted" data-todo-x-show="value === 1" data-todo-colon-className="{ 'text-white': selected === 1, 'text-indigo-600': !(selected === 1) }" className="absolute inset-y-0 right-0 flex items-center pr-4">
                <svg className="h-5 w-5" data-todo-x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
  <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd"></path>
</svg>
              </span>
            </li>
          
            <li data-todo-x-description="Select option, manage highlight styles based on mouseenter/mouseleave and keyboard navigation." data-todo-x-state-on="Highlighted" data-todo-x-state-off="Not Highlighted" id="listbox-item-2" role="option" data-todo-at-click="choose(2)" data-todo-at-mouseenter="selected = 2" data-todo-at-mouseleave="selected = null" data-todo-colon-className="{ 'text-white bg-indigo-600': selected === 2, 'text-gray-900': !(selected === 2) }" className="text-gray-900 cursor-default select-none relative py-2 pl-3 pr-9">
              <div className="flex items-center">
                <span data-todo-x-state-on="Online" data-todo-x-state-off="Not Online" data-todo-colon-className="{ 'bg-green-400': [true,false,false,true,false,true,true,false,true,false][2], 'bg-gray-200': !([true,false,false,true,false,true,true,false,true,false][2])}" className="bg-gray-200 flex-shrink-0 inline-block h-2 w-2 rounded-full" aria-hidden="true"></span>
                <span data-todo-x-state-on="Selected" data-todo-x-state-off="Not Selected" data-todo-colon-className="{ 'font-semibold': value === 2, 'font-normal': !(value === 2) }" className="ml-3 font-normal block truncate">
                  Devon Webb
                  <span className="sr-only"> is offline</span>
                </span>
              </div>

              <span data-todo-x-description="Checkmark, only display for selected option." data-todo-x-state-on="Highlighted" data-todo-x-state-off="Not Highlighted" data-todo-x-show="value === 2" data-todo-colon-className="{ 'text-white': selected === 2, 'text-indigo-600': !(selected === 2) }" className="absolute inset-y-0 right-0 flex items-center pr-4">
                <svg className="h-5 w-5" data-todo-x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
  <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd"></path>
</svg>
              </span>
            </li>
          
            <li data-todo-x-description="Select option, manage highlight styles based on mouseenter/mouseleave and keyboard navigation." data-todo-x-state-on="Highlighted" data-todo-x-state-off="Not Highlighted" id="listbox-item-3" role="option" data-todo-at-click="choose(3)" data-todo-at-mouseenter="selected = 3" data-todo-at-mouseleave="selected = null" data-todo-colon-className="{ 'text-white bg-indigo-600': selected === 3, 'text-gray-900': !(selected === 3) }" className="text-gray-900 cursor-default select-none relative py-2 pl-3 pr-9">
              <div className="flex items-center">
                <span data-todo-x-state-on="Online" data-todo-x-state-off="Not Online" data-todo-colon-className="{ 'bg-green-400': [true,false,false,true,false,true,true,false,true,false][3], 'bg-gray-200': !([true,false,false,true,false,true,true,false,true,false][3])}" className="bg-green-400 flex-shrink-0 inline-block h-2 w-2 rounded-full" aria-hidden="true"></span>
                <span data-todo-x-state-on="Selected" data-todo-x-state-off="Not Selected" data-todo-colon-className="{ 'font-semibold': value === 3, 'font-normal': !(value === 3) }" className="ml-3 font-normal block truncate">
                  Tom Cook
                  <span className="sr-only"> is online</span>
                </span>
              </div>

              <span data-todo-x-description="Checkmark, only display for selected option." data-todo-x-state-on="Highlighted" data-todo-x-state-off="Not Highlighted" data-todo-x-show="value === 3" data-todo-colon-className="{ 'text-white': selected === 3, 'text-indigo-600': !(selected === 3) }" className="absolute inset-y-0 right-0 flex items-center pr-4">
                <svg className="h-5 w-5" data-todo-x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
  <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd"></path>
</svg>
              </span>
            </li>
          
            <li data-todo-x-description="Select option, manage highlight styles based on mouseenter/mouseleave and keyboard navigation." data-todo-x-state-on="Highlighted" data-todo-x-state-off="Not Highlighted" id="listbox-item-4" role="option" data-todo-at-click="choose(4)" data-todo-at-mouseenter="selected = 4" data-todo-at-mouseleave="selected = null" data-todo-colon-className="{ 'text-white bg-indigo-600': selected === 4, 'text-gray-900': !(selected === 4) }" className="text-gray-900 cursor-default select-none relative py-2 pl-3 pr-9">
              <div className="flex items-center">
                <span data-todo-x-state-on="Online" data-todo-x-state-off="Not Online" data-todo-colon-className="{ 'bg-green-400': [true,false,false,true,false,true,true,false,true,false][4], 'bg-gray-200': !([true,false,false,true,false,true,true,false,true,false][4])}" className="bg-gray-200 flex-shrink-0 inline-block h-2 w-2 rounded-full" aria-hidden="true"></span>
                <span data-todo-x-state-on="Selected" data-todo-x-state-off="Not Selected" data-todo-colon-className="{ 'font-semibold': value === 4, 'font-normal': !(value === 4) }" className="ml-3 font-normal block truncate">
                  Tanya Fox
                  <span className="sr-only"> is offline</span>
                </span>
              </div>

              <span data-todo-x-description="Checkmark, only display for selected option." data-todo-x-state-on="Highlighted" data-todo-x-state-off="Not Highlighted" data-todo-x-show="value === 4" data-todo-colon-className="{ 'text-white': selected === 4, 'text-indigo-600': !(selected === 4) }" className="absolute inset-y-0 right-0 flex items-center pr-4">
                <svg className="h-5 w-5" data-todo-x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
  <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd"></path>
</svg>
              </span>
            </li>
          
            <li data-todo-x-description="Select option, manage highlight styles based on mouseenter/mouseleave and keyboard navigation." data-todo-x-state-on="Highlighted" data-todo-x-state-off="Not Highlighted" id="listbox-item-5" role="option" data-todo-at-click="choose(5)" data-todo-at-mouseenter="selected = 5" data-todo-at-mouseleave="selected = null" data-todo-colon-className="{ 'text-white bg-indigo-600': selected === 5, 'text-gray-900': !(selected === 5) }" className="text-gray-900 cursor-default select-none relative py-2 pl-3 pr-9">
              <div className="flex items-center">
                <span data-todo-x-state-on="Online" data-todo-x-state-off="Not Online" data-todo-colon-className="{ 'bg-green-400': [true,false,false,true,false,true,true,false,true,false][5], 'bg-gray-200': !([true,false,false,true,false,true,true,false,true,false][5])}" className="bg-green-400 flex-shrink-0 inline-block h-2 w-2 rounded-full" aria-hidden="true"></span>
                <span data-todo-x-state-on="Selected" data-todo-x-state-off="Not Selected" data-todo-colon-className="{ 'font-semibold': value === 5, 'font-normal': !(value === 5) }" className="ml-3 font-normal block truncate">
                  Hellen Schmidt
                  <span className="sr-only"> is online</span>
                </span>
              </div>

              <span data-todo-x-description="Checkmark, only display for selected option." data-todo-x-state-on="Highlighted" data-todo-x-state-off="Not Highlighted" data-todo-x-show="value === 5" data-todo-colon-className="{ 'text-white': selected === 5, 'text-indigo-600': !(selected === 5) }" className="absolute inset-y-0 right-0 flex items-center pr-4">
                <svg className="h-5 w-5" data-todo-x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
  <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd"></path>
</svg>
              </span>
            </li>
          
            <li data-todo-x-description="Select option, manage highlight styles based on mouseenter/mouseleave and keyboard navigation." data-todo-x-state-on="Highlighted" data-todo-x-state-off="Not Highlighted" id="listbox-item-6" role="option" data-todo-at-click="choose(6)" data-todo-at-mouseenter="selected = 6" data-todo-at-mouseleave="selected = null" data-todo-colon-className="{ 'text-white bg-indigo-600': selected === 6, 'text-gray-900': !(selected === 6) }" className="text-gray-900 cursor-default select-none relative py-2 pl-3 pr-9">
              <div className="flex items-center">
                <span data-todo-x-state-on="Online" data-todo-x-state-off="Not Online" data-todo-colon-className="{ 'bg-green-400': [true,false,false,true,false,true,true,false,true,false][6], 'bg-gray-200': !([true,false,false,true,false,true,true,false,true,false][6])}" className="bg-green-400 flex-shrink-0 inline-block h-2 w-2 rounded-full" aria-hidden="true"></span>
                <span data-todo-x-state-on="Selected" data-todo-x-state-off="Not Selected" data-todo-colon-className="{ 'font-semibold': value === 6, 'font-normal': !(value === 6) }" className="ml-3 font-normal block truncate">
                  Caroline Schultz
                  <span className="sr-only"> is online</span>
                </span>
              </div>

              <span data-todo-x-description="Checkmark, only display for selected option." data-todo-x-state-on="Highlighted" data-todo-x-state-off="Not Highlighted" data-todo-x-show="value === 6" data-todo-colon-className="{ 'text-white': selected === 6, 'text-indigo-600': !(selected === 6) }" className="absolute inset-y-0 right-0 flex items-center pr-4">
                <svg className="h-5 w-5" data-todo-x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
  <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd"></path>
</svg>
              </span>
            </li>
          
            <li data-todo-x-description="Select option, manage highlight styles based on mouseenter/mouseleave and keyboard navigation." data-todo-x-state-on="Highlighted" data-todo-x-state-off="Not Highlighted" id="listbox-item-7" role="option" data-todo-at-click="choose(7)" data-todo-at-mouseenter="selected = 7" data-todo-at-mouseleave="selected = null" data-todo-colon-className="{ 'text-white bg-indigo-600': selected === 7, 'text-gray-900': !(selected === 7) }" className="text-gray-900 cursor-default select-none relative py-2 pl-3 pr-9">
              <div className="flex items-center">
                <span data-todo-x-state-on="Online" data-todo-x-state-off="Not Online" data-todo-colon-className="{ 'bg-green-400': [true,false,false,true,false,true,true,false,true,false][7], 'bg-gray-200': !([true,false,false,true,false,true,true,false,true,false][7])}" className="bg-gray-200 flex-shrink-0 inline-block h-2 w-2 rounded-full" aria-hidden="true"></span>
                <span data-todo-x-state-on="Selected" data-todo-x-state-off="Not Selected" data-todo-colon-className="{ 'font-semibold': value === 7, 'font-normal': !(value === 7) }" className="ml-3 font-normal block truncate">
                  Mason Heaney
                  <span className="sr-only"> is offline</span>
                </span>
              </div>

              <span data-todo-x-description="Checkmark, only display for selected option." data-todo-x-state-on="Highlighted" data-todo-x-state-off="Not Highlighted" data-todo-x-show="value === 7" data-todo-colon-className="{ 'text-white': selected === 7, 'text-indigo-600': !(selected === 7) }" className="absolute inset-y-0 right-0 flex items-center pr-4">
                <svg className="h-5 w-5" data-todo-x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
  <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd"></path>
</svg>
              </span>
            </li>
          
            <li data-todo-x-description="Select option, manage highlight styles based on mouseenter/mouseleave and keyboard navigation." data-todo-x-state-on="Highlighted" data-todo-x-state-off="Not Highlighted" id="listbox-item-8" role="option" data-todo-at-click="choose(8)" data-todo-at-mouseenter="selected = 8" data-todo-at-mouseleave="selected = null" data-todo-colon-className="{ 'text-white bg-indigo-600': selected === 8, 'text-gray-900': !(selected === 8) }" className="text-gray-900 cursor-default select-none relative py-2 pl-3 pr-9">
              <div className="flex items-center">
                <span data-todo-x-state-on="Online" data-todo-x-state-off="Not Online" data-todo-colon-className="{ 'bg-green-400': [true,false,false,true,false,true,true,false,true,false][8], 'bg-gray-200': !([true,false,false,true,false,true,true,false,true,false][8])}" className="bg-green-400 flex-shrink-0 inline-block h-2 w-2 rounded-full" aria-hidden="true"></span>
                <span data-todo-x-state-on="Selected" data-todo-x-state-off="Not Selected" data-todo-colon-className="{ 'font-semibold': value === 8, 'font-normal': !(value === 8) }" className="ml-3 font-normal block truncate">
                  Claudie Smitham
                  <span className="sr-only"> is online</span>
                </span>
              </div>

              <span data-todo-x-description="Checkmark, only display for selected option." data-todo-x-state-on="Highlighted" data-todo-x-state-off="Not Highlighted" data-todo-x-show="value === 8" data-todo-colon-className="{ 'text-white': selected === 8, 'text-indigo-600': !(selected === 8) }" className="absolute inset-y-0 right-0 flex items-center pr-4">
                <svg className="h-5 w-5" data-todo-x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
  <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd"></path>
</svg>
              </span>
            </li>
          
            <li data-todo-x-description="Select option, manage highlight styles based on mouseenter/mouseleave and keyboard navigation." data-todo-x-state-on="Highlighted" data-todo-x-state-off="Not Highlighted" id="listbox-item-9" role="option" data-todo-at-click="choose(9)" data-todo-at-mouseenter="selected = 9" data-todo-at-mouseleave="selected = null" data-todo-colon-className="{ 'text-white bg-indigo-600': selected === 9, 'text-gray-900': !(selected === 9) }" className="text-gray-900 cursor-default select-none relative py-2 pl-3 pr-9">
              <div className="flex items-center">
                <span data-todo-x-state-on="Online" data-todo-x-state-off="Not Online" data-todo-colon-className="{ 'bg-green-400': [true,false,false,true,false,true,true,false,true,false][9], 'bg-gray-200': !([true,false,false,true,false,true,true,false,true,false][9])}" className="bg-gray-200 flex-shrink-0 inline-block h-2 w-2 rounded-full" aria-hidden="true"></span>
                <span data-todo-x-state-on="Selected" data-todo-x-state-off="Not Selected" data-todo-colon-className="{ 'font-semibold': value === 9, 'font-normal': !(value === 9) }" className="ml-3 font-normal block truncate">
                  Emil Schaefer
                  <span className="sr-only"> is offline</span>
                </span>
              </div>

              <span data-todo-x-description="Checkmark, only display for selected option." data-todo-x-state-on="Highlighted" data-todo-x-state-off="Not Highlighted" data-todo-x-show="value === 9" data-todo-colon-className="{ 'text-white': selected === 9, 'text-indigo-600': !(selected === 9) }" className="absolute inset-y-0 right-0 flex items-center pr-4">
                <svg className="h-5 w-5" data-todo-x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
  <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd"></path>
</svg>
              </span>
            </li>
          
        </ul>
      </div>
    </div>
  </div>

    </div>
  </div>
</>
);

ReactDOM.render(<Component/>, document.getElementById('root'));

// vue/components/application-ui/forms/select-menus/custom_with_status_indicator.vue
<template>
    <div class="p-8 flex justify-center bg-gray-100" style="min-height: 600px;">
      <div class="w-full max-w-xs mx-auto">
      
    <!--
    Custom select controls like this require a considerable amount of JS to implement from scratch. We're planning
    to build some low-level libraries to make this easier with popular frameworks like React, Vue, and even Alpine.js
    in the near future, but in the mean time we recommend these reference guides when building your implementation:

    https://www.w3.org/TR/wai-aria-practices/#Listbox
    https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html
  -->
    <div x-data="Components.customSelect({ open: true, value: 3, selected: 3 })" x-init="init()">
      <label id="listbox-label" class="block text-sm font-medium text-gray-700">
        Assigned to
      </label>
      <div class="mt-1 relative">
        <button type="button" x-ref="button" @keydown.arrow-up.stop.prevent="onButtonClick()" @keydown.arrow-down.stop.prevent="onButtonClick()" @click="onButtonClick()" aria-haspopup="listbox" :aria-expanded="open" aria-expanded="true" aria-labelledby="listbox-label" class="relative w-full bg-white border border-gray-300 rounded-md shadow-sm pl-3 pr-10 py-2 text-left cursor-default focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
          <div class="flex items-center">
            <span aria-label="Online" :aria-label="[true,false,false,true,false,true,true,false,true,false][value] ? 'Online' : 'Offline'" :class="{ 'bg-green-400': [true,false,false,true,false,true,true,false,true,false][value], 'bg-gray-200': !([true,false,false,true,false,true,true,false,true,false][value])}" class="bg-green-400 flex-shrink-0 inline-block h-2 w-2 rounded-full"></span>
            <span x-text="[&quot;Wade Cooper&quot;,&quot;Arlene Mccoy&quot;,&quot;Devon Webb&quot;,&quot;Tom Cook&quot;,&quot;Tanya Fox&quot;,&quot;Hellen Schmidt&quot;,&quot;Caroline Schultz&quot;,&quot;Mason Heaney&quot;,&quot;Claudie Smitham&quot;,&quot;Emil Schaefer&quot;][value]" class="ml-3 block truncate">
              Tom Cook
            </span>
          </div>
          <span class="absolute inset-y-0 right-0 flex items-center pr-2 pointer-events-none">
            <svg class="h-5 w-5 text-gray-400" x-description="Heroicon name: selector" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
    <path fill-rule="evenodd" d="M10 3a1 1 0 01.707.293l3 3a1 1 0 01-1.414 1.414L10 5.414 7.707 7.707a1 1 0 01-1.414-1.414l3-3A1 1 0 0110 3zm-3.707 9.293a1 1 0 011.414 0L10 14.586l2.293-2.293a1 1 0 011.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z" clip-rule="evenodd"></path>
  </svg>
          </span>
        </button>

        <transition enter-active-class="undefined" enter-class="undefined" enter-to-class="undefined" leave-active-class="transition ease-in duration-100" leave-class="opacity-100" leave-to-class="opacity-0"><div v-if="open" @click.away="open = false" x-description="Select popover, show/hide based on select state." class="absolute mt-1 w-full rounded-md bg-white shadow-lg">
          <ul @keydown.enter.stop.prevent="onOptionSelect()" @keydown.space.stop.prevent="onOptionSelect()" @keydown.escape="onEscape()" @keydown.arrow-up.prevent="onArrowUp()" @keydown.arrow-down.prevent="onArrowDown()" x-ref="listbox" tabindex="-1" role="listbox" aria-labelledby="listbox-label" :aria-activedescendant="activeDescendant" aria-activedescendant="listbox-item-3" class="max-h-60 rounded-md py-1 text-base ring-1 ring-black ring-opacity-5 overflow-auto focus:outline-none sm:text-sm" x-max="1">
          
              <li x-description="Select option, manage highlight styles based on mouseenter/mouseleave and keyboard navigation." x-state:on="Highlighted" x-state:off="Not Highlighted" id="listbox-item-0" role="option" @click="choose(0)" @mouseenter="selected = 0" @mouseleave="selected = null" :class="{ 'text-white bg-indigo-600': selected === 0, 'text-gray-900': !(selected === 0) }" class="text-gray-900 cursor-default select-none relative py-2 pl-3 pr-9">
                <div class="flex items-center">
                  <span x-state:on="Online" x-state:off="Not Online" :class="{ 'bg-green-400': [true,false,false,true,false,true,true,false,true,false][0], 'bg-gray-200': !([true,false,false,true,false,true,true,false,true,false][0])}" class="bg-green-400 flex-shrink-0 inline-block h-2 w-2 rounded-full" aria-hidden="true"></span>
                  <span x-state:on="Selected" x-state:off="Not Selected" :class="{ 'font-semibold': value === 0, 'font-normal': !(value === 0) }" class="ml-3 font-normal block truncate">
                    Wade Cooper
                    <span class="sr-only"> is online</span>
                  </span>
                </div>

                <span x-description="Checkmark, only display for selected option." x-state:on="Highlighted" x-state:off="Not Highlighted" v-if="value === 0" :class="{ 'text-white': selected === 0, 'text-indigo-600': !(selected === 0) }" class="absolute inset-y-0 right-0 flex items-center pr-4">
                  <svg class="h-5 w-5" x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
    <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path>
  </svg>
                </span>
              </li>
          
              <li x-description="Select option, manage highlight styles based on mouseenter/mouseleave and keyboard navigation." x-state:on="Highlighted" x-state:off="Not Highlighted" id="listbox-item-1" role="option" @click="choose(1)" @mouseenter="selected = 1" @mouseleave="selected = null" :class="{ 'text-white bg-indigo-600': selected === 1, 'text-gray-900': !(selected === 1) }" class="text-gray-900 cursor-default select-none relative py-2 pl-3 pr-9">
                <div class="flex items-center">
                  <span x-state:on="Online" x-state:off="Not Online" :class="{ 'bg-green-400': [true,false,false,true,false,true,true,false,true,false][1], 'bg-gray-200': !([true,false,false,true,false,true,true,false,true,false][1])}" class="bg-gray-200 flex-shrink-0 inline-block h-2 w-2 rounded-full" aria-hidden="true"></span>
                  <span x-state:on="Selected" x-state:off="Not Selected" :class="{ 'font-semibold': value === 1, 'font-normal': !(value === 1) }" class="ml-3 font-normal block truncate">
                    Arlene Mccoy
                    <span class="sr-only"> is offline</span>
                  </span>
                </div>

                <span x-description="Checkmark, only display for selected option." x-state:on="Highlighted" x-state:off="Not Highlighted" v-if="value === 1" :class="{ 'text-white': selected === 1, 'text-indigo-600': !(selected === 1) }" class="absolute inset-y-0 right-0 flex items-center pr-4">
                  <svg class="h-5 w-5" x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
    <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path>
  </svg>
                </span>
              </li>
          
              <li x-description="Select option, manage highlight styles based on mouseenter/mouseleave and keyboard navigation." x-state:on="Highlighted" x-state:off="Not Highlighted" id="listbox-item-2" role="option" @click="choose(2)" @mouseenter="selected = 2" @mouseleave="selected = null" :class="{ 'text-white bg-indigo-600': selected === 2, 'text-gray-900': !(selected === 2) }" class="text-gray-900 cursor-default select-none relative py-2 pl-3 pr-9">
                <div class="flex items-center">
                  <span x-state:on="Online" x-state:off="Not Online" :class="{ 'bg-green-400': [true,false,false,true,false,true,true,false,true,false][2], 'bg-gray-200': !([true,false,false,true,false,true,true,false,true,false][2])}" class="bg-gray-200 flex-shrink-0 inline-block h-2 w-2 rounded-full" aria-hidden="true"></span>
                  <span x-state:on="Selected" x-state:off="Not Selected" :class="{ 'font-semibold': value === 2, 'font-normal': !(value === 2) }" class="ml-3 font-normal block truncate">
                    Devon Webb
                    <span class="sr-only"> is offline</span>
                  </span>
                </div>

                <span x-description="Checkmark, only display for selected option." x-state:on="Highlighted" x-state:off="Not Highlighted" v-if="value === 2" :class="{ 'text-white': selected === 2, 'text-indigo-600': !(selected === 2) }" class="absolute inset-y-0 right-0 flex items-center pr-4">
                  <svg class="h-5 w-5" x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
    <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path>
  </svg>
                </span>
              </li>
          
              <li x-description="Select option, manage highlight styles based on mouseenter/mouseleave and keyboard navigation." x-state:on="Highlighted" x-state:off="Not Highlighted" id="listbox-item-3" role="option" @click="choose(3)" @mouseenter="selected = 3" @mouseleave="selected = null" :class="{ 'text-white bg-indigo-600': selected === 3, 'text-gray-900': !(selected === 3) }" class="text-gray-900 cursor-default select-none relative py-2 pl-3 pr-9">
                <div class="flex items-center">
                  <span x-state:on="Online" x-state:off="Not Online" :class="{ 'bg-green-400': [true,false,false,true,false,true,true,false,true,false][3], 'bg-gray-200': !([true,false,false,true,false,true,true,false,true,false][3])}" class="bg-green-400 flex-shrink-0 inline-block h-2 w-2 rounded-full" aria-hidden="true"></span>
                  <span x-state:on="Selected" x-state:off="Not Selected" :class="{ 'font-semibold': value === 3, 'font-normal': !(value === 3) }" class="ml-3 font-normal block truncate">
                    Tom Cook
                    <span class="sr-only"> is online</span>
                  </span>
                </div>

                <span x-description="Checkmark, only display for selected option." x-state:on="Highlighted" x-state:off="Not Highlighted" v-if="value === 3" :class="{ 'text-white': selected === 3, 'text-indigo-600': !(selected === 3) }" class="absolute inset-y-0 right-0 flex items-center pr-4">
                  <svg class="h-5 w-5" x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
    <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path>
  </svg>
                </span>
              </li>
          
              <li x-description="Select option, manage highlight styles based on mouseenter/mouseleave and keyboard navigation." x-state:on="Highlighted" x-state:off="Not Highlighted" id="listbox-item-4" role="option" @click="choose(4)" @mouseenter="selected = 4" @mouseleave="selected = null" :class="{ 'text-white bg-indigo-600': selected === 4, 'text-gray-900': !(selected === 4) }" class="text-gray-900 cursor-default select-none relative py-2 pl-3 pr-9">
                <div class="flex items-center">
                  <span x-state:on="Online" x-state:off="Not Online" :class="{ 'bg-green-400': [true,false,false,true,false,true,true,false,true,false][4], 'bg-gray-200': !([true,false,false,true,false,true,true,false,true,false][4])}" class="bg-gray-200 flex-shrink-0 inline-block h-2 w-2 rounded-full" aria-hidden="true"></span>
                  <span x-state:on="Selected" x-state:off="Not Selected" :class="{ 'font-semibold': value === 4, 'font-normal': !(value === 4) }" class="ml-3 font-normal block truncate">
                    Tanya Fox
                    <span class="sr-only"> is offline</span>
                  </span>
                </div>

                <span x-description="Checkmark, only display for selected option." x-state:on="Highlighted" x-state:off="Not Highlighted" v-if="value === 4" :class="{ 'text-white': selected === 4, 'text-indigo-600': !(selected === 4) }" class="absolute inset-y-0 right-0 flex items-center pr-4">
                  <svg class="h-5 w-5" x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
    <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path>
  </svg>
                </span>
              </li>
          
              <li x-description="Select option, manage highlight styles based on mouseenter/mouseleave and keyboard navigation." x-state:on="Highlighted" x-state:off="Not Highlighted" id="listbox-item-5" role="option" @click="choose(5)" @mouseenter="selected = 5" @mouseleave="selected = null" :class="{ 'text-white bg-indigo-600': selected === 5, 'text-gray-900': !(selected === 5) }" class="text-gray-900 cursor-default select-none relative py-2 pl-3 pr-9">
                <div class="flex items-center">
                  <span x-state:on="Online" x-state:off="Not Online" :class="{ 'bg-green-400': [true,false,false,true,false,true,true,false,true,false][5], 'bg-gray-200': !([true,false,false,true,false,true,true,false,true,false][5])}" class="bg-green-400 flex-shrink-0 inline-block h-2 w-2 rounded-full" aria-hidden="true"></span>
                  <span x-state:on="Selected" x-state:off="Not Selected" :class="{ 'font-semibold': value === 5, 'font-normal': !(value === 5) }" class="ml-3 font-normal block truncate">
                    Hellen Schmidt
                    <span class="sr-only"> is online</span>
                  </span>
                </div>

                <span x-description="Checkmark, only display for selected option." x-state:on="Highlighted" x-state:off="Not Highlighted" v-if="value === 5" :class="{ 'text-white': selected === 5, 'text-indigo-600': !(selected === 5) }" class="absolute inset-y-0 right-0 flex items-center pr-4">
                  <svg class="h-5 w-5" x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
    <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path>
  </svg>
                </span>
              </li>
          
              <li x-description="Select option, manage highlight styles based on mouseenter/mouseleave and keyboard navigation." x-state:on="Highlighted" x-state:off="Not Highlighted" id="listbox-item-6" role="option" @click="choose(6)" @mouseenter="selected = 6" @mouseleave="selected = null" :class="{ 'text-white bg-indigo-600': selected === 6, 'text-gray-900': !(selected === 6) }" class="text-gray-900 cursor-default select-none relative py-2 pl-3 pr-9">
                <div class="flex items-center">
                  <span x-state:on="Online" x-state:off="Not Online" :class="{ 'bg-green-400': [true,false,false,true,false,true,true,false,true,false][6], 'bg-gray-200': !([true,false,false,true,false,true,true,false,true,false][6])}" class="bg-green-400 flex-shrink-0 inline-block h-2 w-2 rounded-full" aria-hidden="true"></span>
                  <span x-state:on="Selected" x-state:off="Not Selected" :class="{ 'font-semibold': value === 6, 'font-normal': !(value === 6) }" class="ml-3 font-normal block truncate">
                    Caroline Schultz
                    <span class="sr-only"> is online</span>
                  </span>
                </div>

                <span x-description="Checkmark, only display for selected option." x-state:on="Highlighted" x-state:off="Not Highlighted" v-if="value === 6" :class="{ 'text-white': selected === 6, 'text-indigo-600': !(selected === 6) }" class="absolute inset-y-0 right-0 flex items-center pr-4">
                  <svg class="h-5 w-5" x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
    <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path>
  </svg>
                </span>
              </li>
          
              <li x-description="Select option, manage highlight styles based on mouseenter/mouseleave and keyboard navigation." x-state:on="Highlighted" x-state:off="Not Highlighted" id="listbox-item-7" role="option" @click="choose(7)" @mouseenter="selected = 7" @mouseleave="selected = null" :class="{ 'text-white bg-indigo-600': selected === 7, 'text-gray-900': !(selected === 7) }" class="text-gray-900 cursor-default select-none relative py-2 pl-3 pr-9">
                <div class="flex items-center">
                  <span x-state:on="Online" x-state:off="Not Online" :class="{ 'bg-green-400': [true,false,false,true,false,true,true,false,true,false][7], 'bg-gray-200': !([true,false,false,true,false,true,true,false,true,false][7])}" class="bg-gray-200 flex-shrink-0 inline-block h-2 w-2 rounded-full" aria-hidden="true"></span>
                  <span x-state:on="Selected" x-state:off="Not Selected" :class="{ 'font-semibold': value === 7, 'font-normal': !(value === 7) }" class="ml-3 font-normal block truncate">
                    Mason Heaney
                    <span class="sr-only"> is offline</span>
                  </span>
                </div>

                <span x-description="Checkmark, only display for selected option." x-state:on="Highlighted" x-state:off="Not Highlighted" v-if="value === 7" :class="{ 'text-white': selected === 7, 'text-indigo-600': !(selected === 7) }" class="absolute inset-y-0 right-0 flex items-center pr-4">
                  <svg class="h-5 w-5" x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
    <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path>
  </svg>
                </span>
              </li>
          
              <li x-description="Select option, manage highlight styles based on mouseenter/mouseleave and keyboard navigation." x-state:on="Highlighted" x-state:off="Not Highlighted" id="listbox-item-8" role="option" @click="choose(8)" @mouseenter="selected = 8" @mouseleave="selected = null" :class="{ 'text-white bg-indigo-600': selected === 8, 'text-gray-900': !(selected === 8) }" class="text-gray-900 cursor-default select-none relative py-2 pl-3 pr-9">
                <div class="flex items-center">
                  <span x-state:on="Online" x-state:off="Not Online" :class="{ 'bg-green-400': [true,false,false,true,false,true,true,false,true,false][8], 'bg-gray-200': !([true,false,false,true,false,true,true,false,true,false][8])}" class="bg-green-400 flex-shrink-0 inline-block h-2 w-2 rounded-full" aria-hidden="true"></span>
                  <span x-state:on="Selected" x-state:off="Not Selected" :class="{ 'font-semibold': value === 8, 'font-normal': !(value === 8) }" class="ml-3 font-normal block truncate">
                    Claudie Smitham
                    <span class="sr-only"> is online</span>
                  </span>
                </div>

                <span x-description="Checkmark, only display for selected option." x-state:on="Highlighted" x-state:off="Not Highlighted" v-if="value === 8" :class="{ 'text-white': selected === 8, 'text-indigo-600': !(selected === 8) }" class="absolute inset-y-0 right-0 flex items-center pr-4">
                  <svg class="h-5 w-5" x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
    <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path>
  </svg>
                </span>
              </li>
          
              <li x-description="Select option, manage highlight styles based on mouseenter/mouseleave and keyboard navigation." x-state:on="Highlighted" x-state:off="Not Highlighted" id="listbox-item-9" role="option" @click="choose(9)" @mouseenter="selected = 9" @mouseleave="selected = null" :class="{ 'text-white bg-indigo-600': selected === 9, 'text-gray-900': !(selected === 9) }" class="text-gray-900 cursor-default select-none relative py-2 pl-3 pr-9">
                <div class="flex items-center">
                  <span x-state:on="Online" x-state:off="Not Online" :class="{ 'bg-green-400': [true,false,false,true,false,true,true,false,true,false][9], 'bg-gray-200': !([true,false,false,true,false,true,true,false,true,false][9])}" class="bg-gray-200 flex-shrink-0 inline-block h-2 w-2 rounded-full" aria-hidden="true"></span>
                  <span x-state:on="Selected" x-state:off="Not Selected" :class="{ 'font-semibold': value === 9, 'font-normal': !(value === 9) }" class="ml-3 font-normal block truncate">
                    Emil Schaefer
                    <span class="sr-only"> is offline</span>
                  </span>
                </div>

                <span x-description="Checkmark, only display for selected option." x-state:on="Highlighted" x-state:off="Not Highlighted" v-if="value === 9" :class="{ 'text-white': selected === 9, 'text-indigo-600': !(selected === 9) }" class="absolute inset-y-0 right-0 flex items-center pr-4">
                  <svg class="h-5 w-5" x-description="Heroicon name: check" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
    <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path>
  </svg>
                </span>
              </li>
          
          </ul>
        </div></transition>
      </div>
    </div>

      </div>
    </div>
</template>

<script>
export default {
  data: () => ({
	
  })
}
</script>
