// tailwinduikit/prodify/angular/src/app/components/verical-cards-with-bold-number/verical-cards-with-bold-number.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'app-verical-cards-with-bold-number',
    templateUrl: './verical-cards-with-bold-number.component.html',
    styleUrls: ['./verical-cards-with-bold-number.component.css'],
})
export class VericalCardsWithBoldNumberComponent implements OnInit {
    constructor() {}

    ngOnInit(): void {}
}

<div class="mx-auto container mt-14 w-full">
    <div class="px-4 xl:px-0 flex flex-col justify-center items-center w-full">
        <div class="md:w-9/12 lg:w-7/12 pb-8 border-b border-gray-200">
            <h1 class="text-xl text-color-dark f-f-l"><span class="font-bold">Knowledge Base &gt;</span> How to get started with prodify</h1>
            <div>
                <div class="mt-14">
                    <h1 class="text-2xl sm:text-5xl font-black f-f-l text-color pb-5">How to get started with prodify</h1>
                    <h2 class="text-2xl f-f-r text-color-dark">Introductory resources to get you started with using prodify</h2>
                </div>
                <a href="/resources-article">
                    <div class="mt-24">
                        <h1 class="text-xl sm:text-4xl text-color font-bold pb-5 f-f-l">What are the general requirements to onboard</h1>
                        <h2 class="text-xl f-f-r  text-color-dark">The option to add another project can be found in the upload section, as well as on the final submit section what we dont know is that it needs proper installation of the...</h2>
                    </div>
                </a>
                <div class="mt-6 flex items-center">
                    <img class="-ml-2" src="https://cdn.tuk.dev/assets/templates/prodify/AvtarKnowledgeBase(3).png" alt="" />
                    <p class="text-base text-black f-f-r pl-3">Contributed by James Larson</p>
                </div>
            </div>
        </div>
        <div class="md:w-9/12 lg:w-7/12 my-6 md:my-12 pb-8 border-b border-gray-200">
            <div>
                <a href="/resources-article">
                    <div>
                        <h1 class="text-xl sm:text-4xl text-color font-bold pb-5 f-f-l">What are the general requirements to onboard</h1>
                        <h2 class="text-xl f-f-r  text-color-dark">The option to add another project can be found in the upload section, as well as on the final submit section what we dont know is that it needs proper installation of the...</h2>
                    </div>
                </a>
                <div class="mt-6 flex items-center">
                    <img class="-ml-2" src="https://cdn.tuk.dev/assets/templates/prodify/AvtarKnowledgeBase(3).png" alt="" />
                    <p class="text-base text-black f-f-r pl-3">Contributed by James Larson</p>
                </div>
            </div>
        </div>
        <div class="md:w-9/12 lg:w-7/12 my-6 md:my-12 pb-8 border-b border-gray-200">
            <div>
                <a href="/resources-article">
                    <div>
                        <h1 class="text-xl sm:text-4xl text-color font-bold pb-5 f-f-l">What are the general requirements to onboard</h1>
                        <h2 class="text-xl f-f-r  text-color-dark">The option to add another project can be found in the upload section, as well as on the final submit section what we dont know is that it needs proper installation of the...</h2>
                    </div>
                </a>
                <div class="mt-6 flex items-center">
                    <img class="-ml-2" src="https://cdn.tuk.dev/assets/templates/prodify/AvtarKnowledgeBase(3).png" alt="" />
                    <p class="text-base text-black f-f-r pl-3">Contributed by James Larson</p>
                </div>
            </div>
        </div>
        <div class="md:w-9/12 lg:w-7/12 my-6 md:my-12 pb-8 border-b border-gray-200">
            <div>
                <a href="/resources-article">
                    <div>
                        <h1 class="text-xl sm:text-4xl text-color font-bold pb-5 f-f-l">What are the general requirements to onboard</h1>
                        <h2 class="text-xl f-f-r  text-color-dark">The option to add another project can be found in the upload section, as well as on the final submit section what we dont know is that it needs proper installation of the...</h2>
                    </div>
                </a>
                <div class="mt-6 flex items-center">
                    <img class="-ml-2" src="https://cdn.tuk.dev/assets/templates/prodify/AvtarKnowledgeBase(3).png" alt="" />
                    <p class="text-base text-black f-f-r pl-3">Contributed by James Larson</p>
                </div>
            </div>
        </div>
    </div>
</div>

// tailwinduikit/prodify/react/components/verical_cards_with_bold_number/index.js
const Index = (props) => (
    <div className="mx-auto container mt-14 w-full">
        <div className="px-4 xl:px-0 flex flex-col justify-center items-center w-full">
            <div className="md:w-9/12 lg:w-7/12 pb-8 border-b border-gray-200">
                <h1 className="text-xl text-color-dark f-f-l">
                    <span className="font-bold">Knowledge Base &gt;</span> How to get started with prodify
                </h1>
                <div>
                    <div className="mt-14">
                        <h1 className="text-2xl sm:text-5xl font-black f-f-l text-color pb-5">How to get started with prodify</h1>
                        <h2 className="text-2xl f-f-r text-color-dark">Introductory resources to get you started with using prodify</h2>
                    </div>
                    <a href="/knowledge-base-article">
                        <div className="mt-24">
                            <h1 className="text-xl sm:text-4xl text-color font-bold pb-5 f-f-l">What are the general requirements to onboard </h1>
                            <h2 className="text-xl f-f-r">The option to add another project can be found in the upload section, as well as on the final submit section what we dont know is that it needs proper installation of the...</h2>
                        </div>
                    </a>
                    <div className="mt-6 flex items-center">
                        <img className="-ml-2" src="https://cdn.tuk.dev/assets/templates/prodify/AvtarKnowledgeBase(3).png" alt />
                        <p className="text-base text-black f-f-r pl-3">Contributed by James Larson </p>
                    </div>
                </div>
            </div>
            <div className="md:w-9/12 lg:w-7/12 my-6 md:my-12 pb-8 border-b border-gray-200">
                <div>
                    <a href="/knowledge-base-article">
                        <div>
                            <h1 className="text-xl sm:text-4xl text-color font-bold pb-5 f-f-l">What are the general requirements to onboard </h1>
                            <h2 className="text-xl f-f-r">The option to add another project can be found in the upload section, as well as on the final submit section what we dont know is that it needs proper installation of the...</h2>
                        </div>
                    </a>
                    <div className="mt-6 flex items-center">
                        <img className="-ml-2" src="https://cdn.tuk.dev/assets/templates/prodify/AvtarKnowledgeBase(3).png" alt />
                        <p className="text-base text-black f-f-r pl-3">Contributed by James Larson </p>
                    </div>
                </div>
            </div>
            <div className="md:w-9/12 lg:w-7/12 my-6 md:my-12 pb-8 border-b border-gray-200">
                <div>
                    <a href="/knowledge-base-article">
                        <div>
                            <h1 className="text-xl sm:text-4xl text-color font-bold pb-5 f-f-l">What are the general requirements to onboard </h1>
                            <h2 className="text-xl f-f-r">The option to add another project can be found in the upload section, as well as on the final submit section what we dont know is that it needs proper installation of the...</h2>
                        </div>
                    </a>
                    <div className="mt-6 flex items-center">
                        <img className="-ml-2" src="https://cdn.tuk.dev/assets/templates/prodify/AvtarKnowledgeBase(3).png" alt />
                        <p className="text-base text-black f-f-r pl-3">Contributed by James Larson </p>
                    </div>
                </div>
            </div>
            <div className="md:w-9/12 lg:w-7/12 my-6 md:my-12 pb-8 border-b border-gray-200">
                <div>
                    <a href="/knowledge-base-article">
                        <div>
                            <h1 className="text-xl sm:text-4xl text-color font-bold pb-5 f-f-l">What are the general requirements to onboard </h1>
                            <h2 className="text-xl f-f-r">The option to add another project can be found in the upload section, as well as on the final submit section what we dont know is that it needs proper installation of the...</h2>
                        </div>
                    </a>
                    <div className="mt-6 flex items-center">
                        <img className="-ml-2" src="https://cdn.tuk.dev/assets/templates/prodify/AvtarKnowledgeBase(3).png" alt />
                        <p className="text-base text-black f-f-r pl-3">Contributed by James Larson </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
);
export default Index;
