// tailwinduikit/fabterior/vue/src/components/3_placeholders_with_description/index.vue
<template>
    <div class="mx-auto container px-6 lg:mt-40 mt-10">
        <div class="flex flex-col justify-center items-center w-full">
            <h1 class="f-f-d-s text-2xl lg:text-6xl leading-normal tracking-wide custom-gray-800 text-center">What We Have Done So Far</h1>
            <p class="text-2xl font-normal tracking-tight leading-9 py-3 lg:w-3/5 text-color-para text-center f-f-l">Dive into our projects from small businesses to Enterprise solutions. Record of delivering</p>
        </div>
        <div class="mt-5 lg:mt-24">
            <div class="flex lg:flex-row flex-col items-center lg:justify-between pb-14">
                <div class="relative flex mb-5 lg:mb-0 w-1/2">
                    <div class="">
                        <div class="hidden lg:block absolute top-0 z-0">
                            <svg class="" xmlns="http://www.w3.org/2000/svg" width="403" height="527" viewBox="0 0 403 527" fill="none">
                                <rect x="-1.61167" y="1.37931" width="362" height="497" transform="matrix(-0.996996 -0.077453 -0.077453 0.996996 399.607 28.1496)" stroke="#334048" stroke-width="3" />
                            </svg>
                        </div>
                    </div>
                    <div class="z-10 ml-3 mt-4 lg:ml-4 lg:mt-4 hidden lg:block">
                        <img class="w-full" src="https://cdn.tuk.dev/assets/templates/Fabterior/section4(1).jpg" alt="" />
                    </div>
                    <div class="w-full block lg:hidden">
                        <div class="flex items-center justify-center">
                            <div class="w-full h-full absolute top-0 z-0">
                                <svg class="" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 403 527" fill="none">
                                    <rect x="-1.61167" y="1.37931" width="362" height="497" transform="matrix(-0.996996 -0.077453 -0.077453 0.996996 399.607 28.1496)" stroke="#334048" stroke-width="3" />
                                </svg>
                            </div>

                            <div class="z-10 ml-3 mt-4 lg:ml-4 lg:mt-4 w-full h-full">
                                <img class="w-full" src="https://cdn.tuk.dev/assets/templates/Fabterior/section4(1).jpg" alt="" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="flex items-center lg:w-1/2">
                    <div class="hidden lg:block lg:pr-6">
                        <svg xmlns="http://www.w3.org/2000/svg" width="151" height="4" viewBox="0 0 151 4" fill="none">
                            <line x1="0.75" y1="1.63696" x2="150.75" y2="1.63696" stroke="#334048" stroke-width="3" />
                        </svg>
                    </div>
                    <div class="lg:pt-0 lg:pt-5">
                        <div class="font-normal py-4 text-center lg:text-left f-f-d-s custom-gray-800 lg:text-5xl text-2xl">Modern Interior for Luxury Look and Feel</div>
                        <div class="py-3 lg:text-2xl text-base font-normal text-center lg:text-left leading-9 text-color-para f-f-l">Vestibulum placerat scelerisque turpis, ut laoreet erat varius ut. Phasellus eleifend vitae augue a accumsan. Sed eu semper lorem. Nullam sodales lorem libero, ut viverra diam suscipit et. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam ac posuere nunc.</div>
                        <div class="flex lg:block justify-center w-full">
                            <a href="#"><button class="border-b-2 border-gray-800 pt-8 lg:text-2xl text-base focus:outline-none font-bold text-black-color f-f-l">View Project</button></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="flex lg:flex-row flex-col items-center lg:justify-between py-14">
                <div class="sm:hidden relative flex mb-5 lg:mb-0">
                    <div class="">
                        <div class="hidden lg:block absolute top-0 z-0">
                            <svg class="" xmlns="http://www.w3.org/2000/svg" width="403" height="527" viewBox="0 0 403 527" fill="none">
                                <rect x="-1.61167" y="1.37931" width="362" height="497" transform="matrix(-0.996996 -0.077453 -0.077453 0.996996 399.607 28.1496)" stroke="#334048" stroke-width="3" />
                            </svg>
                        </div>
                        <div class="absolute lg:hidden top-0 z-0">
                            <svg class="" xmlns="http://www.w3.org/2000/svg" width="200" height="300" viewBox="0 0 403 527" fill="none">
                                <rect x="-1.61167" y="1.37931" width="362" height="497" transform="matrix(-0.996996 -0.077453 -0.077453 0.996996 399.607 28.1496)" stroke="#334048" stroke-width="3" />
                            </svg>
                        </div>
                    </div>
                    <div class="z-10 ml-2 mt-6 lg:ml-4 lg:mt-4 w-1/2 lg:w-full">
                        <img class="" src="https://cdn.tuk.dev/assets/templates/Fabterior/section4(2).png" alt="" />
                    </div>
                </div>
                <div class="hidden sm:block md:hidden relative w-full sm:flex md:hidden justify-end mb-5 lg:mb-0">
                    <div class="">
                        <div class="hidden sm:block md:hidden lg:hidden absolute top-0 z-0">
                            <svg class="" xmlns="http://www.w3.org/2000/svg" width="403" height="527" viewBox="0 0 403 527" fill="none">
                                <rect x="-1.61167" y="1.37931" width="362" height="497" transform="matrix(-0.996996 -0.077453 -0.077453 0.996996 399.607 28.1496)" stroke="#334048" stroke-width="3" />
                            </svg>
                        </div>
                        <div class="absolute sm:hidden top-0 z-0">
                            <svg class="" xmlns="http://www.w3.org/2000/svg" width="200" height="300" viewBox="0 0 403 527" fill="none">
                                <rect x="-1.61167" y="1.37931" width="362" height="497" transform="matrix(-0.996996 -0.077453 -0.077453 0.996996 399.607 28.1496)" stroke="#334048" stroke-width="3" />
                            </svg>
                        </div>
                    </div>
                    <div class="z-10 ml-2 mt-6 lg:ml-4 sm:mt-4 w-1/2 sm:w-full lg:w-full">
                        <img class="" src="https://cdn.tuk.dev/assets/templates/Fabterior/section4(2).png" alt="" />
                    </div>
                </div>
                <div class="relative hidden md:flex lg:flex lg:hidden md:mt-4 lg:mt-0">
                    <div class="">
                        <div class="absolute top-0 z-0">
                            <svg xmlns="http://www.w3.org/2000/svg" width="404" height="527" viewBox="0 0 404 527" fill="none">
                                <rect x="2.36119" y="29.8627" width="362" height="497" transform="rotate(-4.44218 2.36119 29.8627)" stroke="#334048" stroke-width="3" />
                            </svg>
                        </div>
                    </div>
                    <div class="z-10 mt-4 ml-4">
                        <img class="" src="https://cdn.tuk.dev/assets/templates/Fabterior/section4(2).png" alt="" />
                    </div>
                </div>
                <div class="flex items-center md:mt-4 lg:mt-0 lg:w-1/2">
                    <div class="lg:pt-5 lg:pt-0">
                        <div class="font-normal py-4 text-center lg:text-left f-f-d-s custom-gray-800 lg:text-5xl text-2xl">Modern Interior for Luxury Look and Feel</div>
                        <div class="py-3 lg:text-2xl text-base font-normal text-center lg:text-left leading-9 text-color-para f-f-l">Vestibulum placerat scelerisque turpis, ut laoreet erat varius ut. Phasellus eleifend vitae augue a accumsan. Sed eu semper lorem. Nullam sodales lorem libero, ut viverra diam suscipit et. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam ac posuere nunc.</div>
                        <div class="flex lg:block justify-center w-full">
                            <a href="#"><button class="border-b-2 border-gray-800 pt-8 lg:text-2xl text-base focus:outline-none font-bold text-black-color f-f-l">View Project</button></a>
                        </div>
                    </div>
                    <div class="hidden lg:block pl-6">
                        <svg xmlns="http://www.w3.org/2000/svg" width="151" height="4" viewBox="0 0 151 4" fill="none">
                            <line x1="0.75" y1="1.63696" x2="150.75" y2="1.63696" stroke="#334048" stroke-width="3" />
                        </svg>
                    </div>
                </div>
                <div class="relative hidden lg:flex justify-end w-1/2">
                    <div class="">
                        <div class="absolute top-0 z-0">
                            <svg xmlns="http://www.w3.org/2000/svg" width="404" height="527" viewBox="0 0 404 527" fill="none">
                                <rect x="2.36119" y="29.8627" width="362" height="497" transform="rotate(-4.44218 2.36119 29.8627)" stroke="#334048" stroke-width="3" />
                            </svg>
                        </div>
                    </div>
                    <div class="z-10 mt-4 ml-4">
                        <img class="" src="https://cdn.tuk.dev/assets/templates/Fabterior/section4(2).png" alt="" />
                    </div>
                </div>
            </div>
            <div class="flex lg:flex-row flex-col items-center lg:justify-between py-14">
                <div class="relative flex mb-5 lg:mb-0 w-1/2">
                    <div class="">
                        <div class="hidden lg:block absolute top-0 z-0">
                            <svg class="" xmlns="http://www.w3.org/2000/svg" width="403" height="527" viewBox="0 0 403 527" fill="none">
                                <rect x="-1.61167" y="1.37931" width="362" height="497" transform="matrix(-0.996996 -0.077453 -0.077453 0.996996 399.607 28.1496)" stroke="#334048" stroke-width="3" />
                            </svg>
                        </div>
                    </div>
                    <div class="z-10 ml-3 mt-4 lg:ml-4 lg:mt-4 hidden lg:block">
                        <img class="w-full" src="https://cdn.tuk.dev/assets/templates/Fabterior/section4(1).jpg" alt="" />
                    </div>
                    <div class="w-full block lg:hidden">
                        <div class="flex items-center justify-center">
                            <div class="w-full h-full absolute top-0 z-0">
                                <svg class="" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 403 527" fill="none">
                                    <rect x="-1.61167" y="1.37931" width="362" height="497" transform="matrix(-0.996996 -0.077453 -0.077453 0.996996 399.607 28.1496)" stroke="#334048" stroke-width="3" />
                                </svg>
                            </div>

                            <div class="z-10 ml-3 mt-4 lg:ml-4 lg:mt-4 w-full h-full">
                                <img class="w-full" src="https://cdn.tuk.dev/assets/templates/Fabterior/section4(3).png" alt="" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="flex items-center lg:w-1/2">
                    <div class="hidden lg:block lg:pr-6">
                        <svg xmlns="http://www.w3.org/2000/svg" width="151" height="4" viewBox="0 0 151 4" fill="none">
                            <line x1="0.75" y1="1.63696" x2="150.75" y2="1.63696" stroke="#334048" stroke-width="3" />
                        </svg>
                    </div>
                    <div class="lg:pt-0 lg:pt-5">
                        <div class="font-normal py-4 text-center lg:text-left f-f-d-s custom-gray-800 lg:text-5xl text-2xl">Modern Interior for Luxury Look and Feel</div>
                        <div class="py-3 lg:text-2xl text-base font-normal text-center lg:text-left leading-9 text-color-para f-f-l">Vestibulum placerat scelerisque turpis, ut laoreet erat varius ut. Phasellus eleifend vitae augue a accumsan. Sed eu semper lorem. Nullam sodales lorem libero, ut viverra diam suscipit et. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam ac posuere nunc.</div>
                        <div class="flex lg:block justify-center w-full">
                            <a href="#"><button class="border-b-2 border-gray-800 pt-8 lg:text-2xl text-base focus:outline-none font-bold text-black-color f-f-l">View Project</button></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<style>
.text-color-para {
    color: #636363;
}
.text-color-heading {
    color: #334048;
}
</style>

// tailwinduikit/fabterior/react/components/3_placeholders_with_description/index.js
import React from "react";
export default function IndexPage() {
    return (
        <>
            <div className="mx-auto container px-6 lg:mt-40 mt-10">
                <div className="flex flex-col justify-center items-center w-full">
                    <h1 className="f-f-d-s text-2xl lg:text-6xl leading-normal tracking-wide custom-gray-800 text-center">What We Have Done So Far</h1>
                    <p className="text-2xl font-normal tracking-tight leading-9 py-3 lg:w-3/5 text-color-para text-center f-f-l">Dive into our projects from small businesses to Enterprise solutions. Record of delivering</p>
                </div>
                <div className="mt-5 lg:mt-24">
                    <div className="flex lg:flex-row flex-col items-center lg:justify-between pb-14">
                        <div className="relative flex mb-5 lg:mb-0 w-1/2">
                            <div className>
                                <div className="hidden lg:block absolute top-0 z-0">
                                    <svg className xmlns width={403} height={527} viewBox="0 0 403 527" fill="none">
                                        <rect x="-1.61167" y="1.37931" width={362} height={497} transform="matrix(-0.996996 -0.077453 -0.077453 0.996996 399.607 28.1496)" stroke="#334048" strokeWidth={3} />
                                    </svg>
                                </div>
                            </div>
                            <div className="z-10 ml-3 mt-4 lg:ml-4 lg:mt-4 hidden lg:block">
                                <img className="w-full" src="https://cdn.tuk.dev/assets/templates/Fabterior/section4(1).jpg" alt />
                            </div>
                            <div className="w-full block lg:hidden">
                                <div className="flex items-center justify-center">
                                    <div className="w-full h-full absolute top-0 z-0">
                                        <svg className xmlns viewBox="0 0 403 527" fill="none">
                                            <rect x="-1.61167" y="1.37931" width={362} height={497} transform="matrix(-0.996996 -0.077453 -0.077453 0.996996 399.607 28.1496)" stroke="#334048" strokeWidth={3} />
                                        </svg>
                                    </div>
                                    <div className="z-10 ml-3 mt-4 lg:ml-4 lg:mt-4 w-full h-full">
                                        <img className="w-full" src="https://cdn.tuk.dev/assets/templates/Fabterior/section4(1).jpg" alt />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="flex items-center lg:w-1/2">
                            <div className="hidden lg:block lg:pr-6">
                                <svg xmlns="http://www.w3.org/2000/svg" width={151} height={4} viewBox="0 0 151 4" fill="none">
                                    <line x1="0.75" y1="1.63696" x2="150.75" y2="1.63696" stroke="#334048" strokeWidth={3} />
                                </svg>
                            </div>
                            <div className="lg:pt-0 lg:pt-5">
                                <div className="font-normal py-4 text-center lg:text-left f-f-d-s custom-gray-800 lg:text-5xl text-2xl">Modern Interior for Luxury Look and Feel</div>
                                <div className="py-3 lg:text-2xl text-base font-normal text-center lg:text-left leading-9 text-color-para f-f-l">Vestibulum placerat scelerisque turpis, ut laoreet erat varius ut. Phasellus eleifend vitae augue a accumsan. Sed eu semper lorem. Nullam sodales lorem libero, ut viverra diam suscipit et. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam ac posuere nunc.</div>
                                <div className="flex lg:block justify-center w-full">
                                    <a href="#">
                                        <button className="border-b-2 border-gray-800 pt-8 lg:text-2xl text-base focus:outline-none font-bold custom-gray-800 f-f-l">View Project</button>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="flex lg:flex-row flex-col items-center lg:justify-between py-14">
                        <div className="sm:hidden relative flex mb-5 lg:mb-0">
                            <div className>
                                <div className="hidden lg:block absolute top-0 z-0">
                                    <svg className xmlns width={403} height={527} viewBox="0 0 403 527" fill="none">
                                        <rect x="-1.61167" y="1.37931" width={362} height={497} transform="matrix(-0.996996 -0.077453 -0.077453 0.996996 399.607 28.1496)" stroke="#334048" strokeWidth={3} />
                                    </svg>
                                </div>
                                <div className="absolute lg:hidden top-0 z-0">
                                    <svg className xmlns width={200} height={300} viewBox="0 0 403 527" fill="none">
                                        <rect x="-1.61167" y="1.37931" width={362} height={497} transform="matrix(-0.996996 -0.077453 -0.077453 0.996996 399.607 28.1496)" stroke="#334048" strokeWidth={3} />
                                    </svg>
                                </div>
                            </div>
                            <div className="z-10 ml-2 mt-6 lg:ml-4 lg:mt-4 w-1/2 lg:w-full">
                                <img className src="https://cdn.tuk.dev/assets/templates/Fabterior/section4(2).png" alt />
                            </div>
                        </div>
                        <div className="hidden sm:block md:hidden relative w-full sm:flex md:hidden justify-end mb-5 lg:mb-0">
                            <div className>
                                <div className="hidden sm:block md:hidden lg:hidden absolute top-0 z-0">
                                    <svg className xmlns width={403} height={527} viewBox="0 0 403 527" fill="none">
                                        <rect x="-1.61167" y="1.37931" width={362} height={497} transform="matrix(-0.996996 -0.077453 -0.077453 0.996996 399.607 28.1496)" stroke="#334048" strokeWidth={3} />
                                    </svg>
                                </div>
                                <div className="absolute sm:hidden top-0 z-0">
                                    <svg className xmlns width={200} height={300} viewBox="0 0 403 527" fill="none">
                                        <rect x="-1.61167" y="1.37931" width={362} height={497} transform="matrix(-0.996996 -0.077453 -0.077453 0.996996 399.607 28.1496)" stroke="#334048" strokeWidth={3} />
                                    </svg>
                                </div>
                            </div>
                            <div className="z-10 ml-2 mt-6 lg:ml-4 sm:mt-4 w-1/2 sm:w-full lg:w-full">
                                <img className src="https://cdn.tuk.dev/assets/templates/Fabterior/section4(2).png" alt />
                            </div>
                        </div>
                        <div className="relative hidden md:flex lg:flex lg:hidden md:mt-4 lg:mt-0">
                            <div className>
                                <div className="absolute top-0 z-0">
                                    <svg xmlns="http://www.w3.org/2000/svg" width={404} height={527} viewBox="0 0 404 527" fill="none">
                                        <rect x="2.36119" y="29.8627" width={362} height={497} transform="rotate(-4.44218 2.36119 29.8627)" stroke="#334048" strokeWidth={3} />
                                    </svg>
                                </div>
                            </div>
                            <div className="z-10 mt-4 ml-4">
                                <img className src="https://cdn.tuk.dev/assets/templates/Fabterior/section4(2).png" alt />
                            </div>
                        </div>
                        <div className="flex items-center md:mt-4 lg:mt-0 lg:w-1/2">
                            <div className="lg:pt-5 lg:pt-0">
                                <div className="font-normal py-4 text-center lg:text-left f-f-d-s custom-gray-800 lg:text-5xl text-2xl">Modern Interior for Luxury Look and Feel</div>
                                <div className="py-3 lg:text-2xl text-base font-normal text-center lg:text-left leading-9 text-color-para f-f-l">Vestibulum placerat scelerisque turpis, ut laoreet erat varius ut. Phasellus eleifend vitae augue a accumsan. Sed eu semper lorem. Nullam sodales lorem libero, ut viverra diam suscipit et. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam ac posuere nunc.</div>
                                <div className="flex lg:block justify-center w-full">
                                    <a href="#">
                                        <button className="border-b-2 border-gray-800 pt-8 lg:text-2xl text-base focus:outline-none font-bold custom-gray-800 f-f-l">View Project</button>
                                    </a>
                                </div>
                            </div>
                            <div className="hidden lg:block pl-6">
                                <svg xmlns="http://www.w3.org/2000/svg" width={151} height={4} viewBox="0 0 151 4" fill="none">
                                    <line x1="0.75" y1="1.63696" x2="150.75" y2="1.63696" stroke="#334048" strokeWidth={3} />
                                </svg>
                            </div>
                        </div>
                        <div className="relative hidden lg:flex justify-end w-1/2">
                            <div className>
                                <div className="absolute top-0 z-0">
                                    <svg xmlns="http://www.w3.org/2000/svg" width={404} height={527} viewBox="0 0 404 527" fill="none">
                                        <rect x="2.36119" y="29.8627" width={362} height={497} transform="rotate(-4.44218 2.36119 29.8627)" stroke="#334048" strokeWidth={3} />
                                    </svg>
                                </div>
                            </div>
                            <div className="z-10 mt-4 ml-4">
                                <img className src="https://cdn.tuk.dev/assets/templates/Fabterior/section4(2).png" alt />
                            </div>
                        </div>
                    </div>
                    <div className="flex lg:flex-row flex-col items-center lg:justify-between py-14">
                        <div className="relative flex mb-5 lg:mb-0 w-1/2">
                            <div className>
                                <div className="hidden lg:block absolute top-0 z-0">
                                    <svg className xmlns width={403} height={527} viewBox="0 0 403 527" fill="none">
                                        <rect x="-1.61167" y="1.37931" width={362} height={497} transform="matrix(-0.996996 -0.077453 -0.077453 0.996996 399.607 28.1496)" stroke="#334048" strokeWidth={3} />
                                    </svg>
                                </div>
                            </div>
                            <div className="z-10 ml-3 mt-4 lg:ml-4 lg:mt-4 hidden lg:block">
                                <img className="w-full" src="https://cdn.tuk.dev/assets/templates/Fabterior/section4(1).jpg" alt />
                            </div>
                            <div className="w-full block lg:hidden">
                                <div className="flex items-center justify-center">
                                    <div className="w-full h-full absolute top-0 z-0">
                                        <svg className xmlns viewBox="0 0 403 527" fill="none">
                                            <rect x="-1.61167" y="1.37931" width={362} height={497} transform="matrix(-0.996996 -0.077453 -0.077453 0.996996 399.607 28.1496)" stroke="#334048" strokeWidth={3} />
                                        </svg>
                                    </div>
                                    <div className="z-10 ml-3 mt-4 lg:ml-4 lg:mt-4 w-full h-full">
                                        <img className="w-full" src="https://cdn.tuk.dev/assets/templates/Fabterior/section4(3).png" alt />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="flex items-center lg:w-1/2">
                            <div className="hidden lg:block lg:pr-6">
                                <svg xmlns="http://www.w3.org/2000/svg" width={151} height={4} viewBox="0 0 151 4" fill="none">
                                    <line x1="0.75" y1="1.63696" x2="150.75" y2="1.63696" stroke="#334048" strokeWidth={3} />
                                </svg>
                            </div>
                            <div className="lg:pt-0 lg:pt-5">
                                <div className="font-normal py-4 text-center lg:text-left f-f-d-s custom-gray-800 lg:text-5xl text-2xl">Modern Interior for Luxury Look and Feel</div>
                                <div className="py-3 lg:text-2xl text-base font-normal text-center lg:text-left leading-9 text-color-para f-f-l">Vestibulum placerat scelerisque turpis, ut laoreet erat varius ut. Phasellus eleifend vitae augue a accumsan. Sed eu semper lorem. Nullam sodales lorem libero, ut viverra diam suscipit et. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam ac posuere nunc.</div>
                                <div className="flex lg:block justify-center w-full">
                                    <a href="#">
                                        <button className="border-b-2 border-gray-800 pt-8 lg:text-2xl text-base focus:outline-none font-bold custom-gray-800 f-f-l">View Project</button>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <style>
                {`.text-color-para {
            color: #636363;
        }
        .text-color-heading {
            color: #334048;
        }
        .f-f-l {
            font-family: "Roboto", sans-serif;
        }
        .f-f-d-s {
            font-family: "DM Serif Display", serif;
        }
        .font-lato {
            font-family: "Lato", sans-serif;
        }`}
            </style>
        </>
    );
}
