// tailwinduikit/prodify/react/components/verical_cards_with_bold_numbering/index.js
import React from "react";
function IndexPage() {
    return (
        <>
            <div className="mx-auto container px-4 lg:px-0 my-12">
                <div className="w-full flex justify-center flex-col items-center">
                    <div className="bg-white lg:w-11/12 px-6 lg:px-16 py-16 shadow-lg rounded-xl">
                        <div className="lg:flex justify-between  w-full">
                            <div>
                                <div className="pb-6 lg:pb-12">
                                    <h1 className="f-f-l text-xl lg:text-4xl font-black">How to get started with prodify</h1>
                                    <h2 className="f-f-r pt-5 text-base lg:text-2xl">Introductory resources to get you started with using prodify</h2>
                                </div>
                                <div className="pb-6 lg:pb-12">
                                    <h1 className="f-f-r lg:text-2xl underline cursor-pointer text-color-knowledge-base-links pb-5">1. How to setup your workspace in less than 10 minutes</h1>
                                    <h1 className="f-f-r lg:text-2xl underline cursor-pointer text-color-knowledge-base-links pb-5">2. Bringing your team upto speed with real-time collaboration</h1>
                                </div>
                                <div className="xl:flex items-center">
                                    <div className="flex items-center mr-4">
                                        <img src="https://cdn.tuk.dev/assets/templates/prodify/AvtarKnowledgeBase(1).png" alt />
                                        <img className="-ml-8" src="https://cdn.tuk.dev/assets/templates/prodify/AvtarKnowledgeBase(2).png" alt />
                                        <img className="-ml-8" src="https://cdn.tuk.dev/assets/templates/prodify/AvtarKnowledgeBase(3).png" alt />
                                    </div>
                                    <p className="text-base py-2 lg:py-0 lg:text-xl text-black f-f-r">Contributed by Adam. J, Jackson Cyrus &amp; James Clark </p>
                                </div>
                            </div>
                            <div className="flex pt-10 lg:pt-0 lg:flex-col items-center justify-between">
                                <a href="/knowledge-base-inner">
                                    <button className="w-16 h-16 rounded-full bg-button-color-about-us flex items-center justify-center">
                                        <svg xmlns="http://www.w3.org/2000/svg" width={32} height={32} viewBox="0 0 32 32" fill="none">
                                            <path d="M21.5627 14.6667L14.4107 7.51473L16.296 5.62939L26.6667 16.0001L16.296 26.3707L14.4107 24.4854L21.5627 17.3334H5.33337V14.6667H21.5627Z" fill="#4A5568" />
                                        </svg>
                                    </button>
                                </a>
                                <div className="flex flex-col items-center">
                                    <h1 className="f-f-l text-color text-4xl lg:text-7xl font-black">06</h1>
                                    <h2 className="f-f-r text-base lg:text-2xl text-color-dark pt-2">Articles</h2>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="bg-white lg:w-11/12 my-8 lg:my-12 px-6 lg:px-16 py-16 shadow-lg rounded-xl">
                        <div className="lg:flex justify-between  w-full">
                            <div>
                                <div className="pb-6 lg:pb-12">
                                    <h1 className="f-f-l text-xl lg:text-4xl font-black">How to get started with prodify</h1>
                                    <h2 className="f-f-r pt-5 text-base lg:text-2xl">Introductory resources to get you started with using prodify</h2>
                                </div>
                                <div className="pb-6 lg:pb-12">
                                    <h1 className="f-f-r lg:text-2xl underline cursor-pointer text-color-knowledge-base-links pb-5">1. How to setup your workspace in less than 10 minutes</h1>
                                    <h1 className="f-f-r lg:text-2xl underline cursor-pointer text-color-knowledge-base-links pb-5">2. Bringing your team upto speed with real-time collaboration</h1>
                                </div>
                                <div className="xl:flex items-center">
                                    <div className="flex items-center mr-4">
                                        <img src="https://cdn.tuk.dev/assets/templates/prodify/AvtarKnowledgeBase(1).png" alt />
                                        <img className="-ml-8" src="https://cdn.tuk.dev/assets/templates/prodify/AvtarKnowledgeBase(2).png" alt />
                                        <img className="-ml-8" src="https://cdn.tuk.dev/assets/templates/prodify/AvtarKnowledgeBase(3).png" alt />
                                    </div>
                                    <p className="text-base py-2 lg:py-0 lg:text-xl text-black f-f-r">Contributed by Adam. J, Jackson Cyrus &amp; James Clark </p>
                                </div>
                            </div>
                            <div className="flex pt-10 lg:pt-0 lg:flex-col items-center justify-between">
                                <a href="/knowledge-base-inner">
                                    <button className="w-16 h-16 rounded-full bg-button-color-about-us flex items-center justify-center">
                                        <svg xmlns="http://www.w3.org/2000/svg" width={32} height={32} viewBox="0 0 32 32" fill="none">
                                            <path d="M21.5627 14.6667L14.4107 7.51473L16.296 5.62939L26.6667 16.0001L16.296 26.3707L14.4107 24.4854L21.5627 17.3334H5.33337V14.6667H21.5627Z" fill="#4A5568" />
                                        </svg>
                                    </button>
                                </a>
                                <div className="flex flex-col items-center">
                                    <h1 className="f-f-l text-color text-4xl lg:text-7xl font-black">08</h1>
                                    <h2 className="f-f-r text-base lg:text-2xl text-color-dark pt-2">Articles</h2>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="bg-white lg:w-11/12 px-6 lg:px-16 py-16 shadow-lg rounded-xl">
                        <div className="lg:flex justify-between  w-full">
                            <div>
                                <div className="pb-6 lg:pb-12">
                                    <h1 className="f-f-l text-xl lg:text-4xl font-black">How to get started with prodify</h1>
                                    <h2 className="f-f-r pt-5 text-base lg:text-2xl">Introductory resources to get you started with using prodify</h2>
                                </div>
                                <div className="pb-6 lg:pb-12">
                                    <h1 className="f-f-r lg:text-2xl underline cursor-pointer text-color-knowledge-base-links pb-5">1. How to setup your workspace in less than 10 minutes</h1>
                                    <h1 className="f-f-r lg:text-2xl underline cursor-pointer text-color-knowledge-base-links pb-5">2. Bringing your team upto speed with real-time collaboration</h1>
                                </div>
                                <div className="xl:flex items-center">
                                    <div className="flex items-center mr-4">
                                        <img src="https://cdn.tuk.dev/assets/templates/prodify/AvtarKnowledgeBase(1).png" alt />
                                        <img className="-ml-8" src="https://cdn.tuk.dev/assets/templates/prodify/AvtarKnowledgeBase(2).png" alt />
                                        <img className="-ml-8" src="https://cdn.tuk.dev/assets/templates/prodify/AvtarKnowledgeBase(3).png" alt />
                                    </div>
                                    <p className="text-base py-2 lg:py-0 lg:text-xl text-black f-f-r">Contributed by Adam. J, Jackson Cyrus &amp; James Clark </p>
                                </div>
                            </div>
                            <div className="flex pt-10 lg:pt-0 lg:flex-col items-center justify-between">
                                <a href="/knowledge-base-inner">
                                    <button className="w-16 h-16 rounded-full bg-button-color-about-us flex items-center justify-center">
                                        <svg xmlns="http://www.w3.org/2000/svg" width={32} height={32} viewBox="0 0 32 32" fill="none">
                                            <path d="M21.5627 14.6667L14.4107 7.51473L16.296 5.62939L26.6667 16.0001L16.296 26.3707L14.4107 24.4854L21.5627 17.3334H5.33337V14.6667H21.5627Z" fill="#4A5568" />
                                        </svg>
                                    </button>
                                </a>
                                <div className="flex flex-col items-center">
                                    <h1 className="f-f-l text-color text-4xl lg:text-7xl font-black">12</h1>
                                    <h2 className="f-f-r text-base lg:text-2xl text-color-dark pt-2">Articles</h2>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <style>
                {`
        .bg-button-color-about-us {
    background-color: #EDF2F7;
}
.text-color-knowledge-base-links {
    color: #2C66E4;
}`}
            </style>
        </>
    );
}

export default IndexPage;

// tailwinduikit/prodify/angular/src/app/components/verical-cards-with-bold-numbering/verical-cards-with-bold-numbering.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'app-verical-cards-with-bold-numbering',
    templateUrl: './verical-cards-with-bold-numbering.component.html',
    styleUrls: ['./verical-cards-with-bold-numbering.component.css'],
})
export class VericalCardsWithBoldNumberingComponent implements OnInit {
    constructor() {}

    ngOnInit(): void {}
}

<div class="mx-auto container px-4 lg:px-0 my-12">
    <div class="w-full flex justify-center flex-col items-center">
        <div class="bg-white lg:w-11/12 px-6 lg:px-16 py-16 shadow-lg rounded-xl">
            <div class="lg:flex justify-between w-full">
                <div>
                    <div class="pb-6 lg:pb-12">
                        <h1 class="f-f-l text-xl lg:text-4xl font-black">How to get started with prodify</h1>
                        <h2 class="f-f-r pt-5 text-base lg:text-2xl">Introductory resources to get you started with using prodify</h2>
                    </div>
                    <div class="pb-6 lg:pb-12">
                        <h1 class="f-f-r lg:text-2xl underline cursor-pointer text-color-knowledge-base-links pb-5">1. How to setup your workspace in less than 10 minutes</h1>
                        <h1 class="f-f-r lg:text-2xl underline cursor-pointer text-color-knowledge-base-links pb-5">2. Bringing your team upto speed with real-time collaboration</h1>
                    </div>
                    <div class="xl:flex items-center">
                        <div class="flex items-center mr-4">
                            <img src="https://cdn.tuk.dev/assets/templates/prodify/AvtarKnowledgeBase(1).png" alt="" />
                            <img class="-ml-8" src="https://cdn.tuk.dev/assets/templates/prodify/AvtarKnowledgeBase(2).png" alt="" />
                            <img class="-ml-8" src="https://cdn.tuk.dev/assets/templates/prodify/AvtarKnowledgeBase(3).png" alt="" />
                        </div>
                        <p class="text-base py-2 lg:py-0 lg:text-xl text-black f-f-r">Contributed by Adam. J, Jackson Cyrus &amp; James Clark</p>
                    </div>
                </div>
                <div class="flex pt-10 lg:pt-0 lg:flex-col items-center justify-between">
                    <a href="/resources-inner">
                        <button class="w-16 h-16 rounded-full bg-button-color-about-us flex items-center justify-center">
                            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32" fill="none">
                                <path d="M21.5627 14.6667L14.4107 7.51473L16.296 5.62939L26.6667 16.0001L16.296 26.3707L14.4107 24.4854L21.5627 17.3334H5.33337V14.6667H21.5627Z" fill="#4A5568"></path>
                            </svg>
                        </button>
                    </a>
                    <div class="flex flex-col items-center">
                        <h1 class="f-f-l text-color text-4xl lg:text-7xl font-black">06</h1>
                        <h2 class="f-f-r text-base lg:text-2xl text-color-dark pt-2">Articles</h2>
                    </div>
                </div>
            </div>
        </div>
        <div class="bg-white lg:w-11/12 my-8 lg:my-12 px-6 lg:px-16 py-16 shadow-lg rounded-xl">
            <div class="lg:flex justify-between w-full">
                <div>
                    <div class="pb-6 lg:pb-12">
                        <h1 class="f-f-l text-xl lg:text-4xl font-black">How to get started with prodify</h1>
                        <h2 class="f-f-r pt-5 text-base lg:text-2xl">Introductory resources to get you started with using prodify</h2>
                    </div>
                    <div class="pb-6 lg:pb-12">
                        <h1 class="f-f-r lg:text-2xl underline cursor-pointer text-color-knowledge-base-links pb-5">1. How to setup your workspace in less than 10 minutes</h1>
                        <h1 class="f-f-r lg:text-2xl underline cursor-pointer text-color-knowledge-base-links pb-5">2. Bringing your team upto speed with real-time collaboration</h1>
                    </div>
                    <div class="xl:flex items-center">
                        <div class="flex items-center mr-4">
                            <img src="https://cdn.tuk.dev/assets/templates/prodify/AvtarKnowledgeBase(1).png" alt="" />
                            <img class="-ml-8" src="https://cdn.tuk.dev/assets/templates/prodify/AvtarKnowledgeBase(2).png" alt="" />
                            <img class="-ml-8" src="https://cdn.tuk.dev/assets/templates/prodify/AvtarKnowledgeBase(3).png" alt="" />
                        </div>
                        <p class="text-base py-2 lg:py-0 lg:text-xl text-black f-f-r">Contributed by Adam. J, Jackson Cyrus &amp; James Clark</p>
                    </div>
                </div>
                <div class="flex pt-10 lg:pt-0 lg:flex-col items-center justify-between">
                    <a href="/resources-inner">
                        <button class="w-16 h-16 rounded-full bg-button-color-about-us flex items-center justify-center">
                            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32" fill="none">
                                <path d="M21.5627 14.6667L14.4107 7.51473L16.296 5.62939L26.6667 16.0001L16.296 26.3707L14.4107 24.4854L21.5627 17.3334H5.33337V14.6667H21.5627Z" fill="#4A5568"></path>
                            </svg>
                        </button>
                    </a>
                    <div class="flex flex-col items-center">
                        <h1 class="f-f-l text-color text-4xl lg:text-7xl font-black">08</h1>
                        <h2 class="f-f-r text-base lg:text-2xl text-color-dark pt-2">Articles</h2>
                    </div>
                </div>
            </div>
        </div>
        <div class="bg-white lg:w-11/12 px-6 lg:px-16 py-16 shadow-lg rounded-xl">
            <div class="lg:flex justify-between w-full">
                <div>
                    <div class="pb-6 lg:pb-12">
                        <h1 class="f-f-l text-xl lg:text-4xl font-black">How to get started with prodify</h1>
                        <h2 class="f-f-r pt-5 text-base lg:text-2xl">Introductory resources to get you started with using prodify</h2>
                    </div>
                    <div class="pb-6 lg:pb-12">
                        <h1 class="f-f-r lg:text-2xl underline cursor-pointer text-color-knowledge-base-links pb-5">1. How to setup your workspace in less than 10 minutes</h1>
                        <h1 class="f-f-r lg:text-2xl underline cursor-pointer text-color-knowledge-base-links pb-5">2. Bringing your team upto speed with real-time collaboration</h1>
                    </div>
                    <div class="xl:flex items-center">
                        <div class="flex items-center mr-4">
                            <img src="https://cdn.tuk.dev/assets/templates/prodify/AvtarKnowledgeBase(1).png" alt="" />
                            <img class="-ml-8" src="https://cdn.tuk.dev/assets/templates/prodify/AvtarKnowledgeBase(2).png" alt="" />
                            <img class="-ml-8" src="https://cdn.tuk.dev/assets/templates/prodify/AvtarKnowledgeBase(3).png" alt="" />
                        </div>
                        <p class="text-base py-2 lg:py-0 lg:text-xl text-black f-f-r">Contributed by Adam. J, Jackson Cyrus &amp; James Clark</p>
                    </div>
                </div>
                <div class="flex pt-10 lg:pt-0 lg:flex-col items-center justify-between">
                    <a href="/resources-inner">
                        <button class="w-16 h-16 rounded-full bg-button-color-about-us flex items-center justify-center">
                            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32" fill="none">
                                <path d="M21.5627 14.6667L14.4107 7.51473L16.296 5.62939L26.6667 16.0001L16.296 26.3707L14.4107 24.4854L21.5627 17.3334H5.33337V14.6667H21.5627Z" fill="#4A5568"></path>
                            </svg>
                        </button>
                    </a>
                    <div class="flex flex-col items-center">
                        <h1 class="f-f-l text-color text-4xl lg:text-7xl font-black">12</h1>
                        <h2 class="f-f-r text-base lg:text-2xl text-color-dark pt-2">Articles</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    .bg-button-color-about-us {
        background-color: #edf2f7;
    }
    .text-color-knowledge-base-links {
        color: #2c66e4;
    }
</style>
