// react/components/marketing/elements/banners/header_centered/index.js
import React from "react";
import ReactDOM from "react-dom";

const Component = (props) => (
<>
<div className="bg-white" style={{minHeight: "16rem"}}>
    
  <div className="relative bg-indigo-600">
    <div className="max-w-7xl mx-auto py-3 px-3 sm:px-6 lg:px-8">
      <div className="pr-16 sm:text-center sm:px-16">
        <p className="font-medium text-white">
          <span className="md:hidden">
            We announced a new product!
          </span>
          <span className="hidden md:inline">
            Big news! We're excited to announce a brand new product.
          </span>
          <span className="block sm:ml-2 sm:inline-block">
            <a href="/" className="text-white font-bold underline"> Learn more <span aria-hidden="true">→</span></a>
          </span>
        </p>
      </div>
      <div className="absolute inset-y-0 right-0 pt-1 pr-1 flex items-start sm:pt-1 sm:pr-2 sm:items-start">
        <button type="button" className="flex p-2 rounded-md hover:bg-indigo-500 focus:outline-none focus:ring-2 focus:ring-white">
          <span className="sr-only">Dismiss</span>
          <svg className="h-6 w-6 text-white" data-todo-x-description="Heroicon name: outline/x" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12"></path>
</svg>
        </button>
      </div>
    </div>
  </div>

  </div>
</>
);

ReactDOM.render(<Component/>, document.getElementById('root'));

// vue/components/marketing/elements/banners/header_centered.vue
<template>
    <div class="bg-white" style="min-height: 16rem;">
    
    <div class="relative bg-indigo-600">
      <div class="max-w-7xl mx-auto py-3 px-3 sm:px-6 lg:px-8">
        <div class="pr-16 sm:text-center sm:px-16">
          <p class="font-medium text-white">
            <span class="md:hidden">
              We announced a new product!
            </span>
            <span class="hidden md:inline">
              Big news! We're excited to announce a brand new product.
            </span>
            <span class="block sm:ml-2 sm:inline-block">
              <a href="#" class="text-white font-bold underline"> Learn more <span aria-hidden="true">→</span></a>
            </span>
          </p>
        </div>
        <div class="absolute inset-y-0 right-0 pt-1 pr-1 flex items-start sm:pt-1 sm:pr-2 sm:items-start">
          <button type="button" class="flex p-2 rounded-md hover:bg-indigo-500 focus:outline-none focus:ring-2 focus:ring-white">
            <span class="sr-only">Dismiss</span>
            <svg class="h-6 w-6 text-white" x-description="Heroicon name: x" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
  </svg>
          </button>
        </div>
      </div>
    </div>

    </div>
</template>

<script>
export default {
  data: () => ({
	
  })
}
</script>
